### ISSUE TITLE
Ionic 2 On-Screen Keyboard Covers Focused Input Element Inside Grid Component

### ISSUE THREAD

**Issue by mikelunn** [ionic-team/ionic#10629]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The onscreen keyboard covers the input element that has focus when used within the grid component.
![current-keyboard](https://cloud.githubusercontent.com/assets/3696624/23522093/b701f98e-ff4f-11e6-8375-2d1b7bdfdac4.gif)

**Expected behavior:**
Given an ion-grid component and a series of ion-row and ion-col components. When an ion-input component resides within an ion-col component, the on-screen keyboard should not cover the input element when it has focus.
 
The below demo does not use the grid/row/col components.
![expected-keyboard](https://cloud.githubusercontent.com/assets/3696624/23521749/40d07b74-ff4e-11e6-9764-32f5875afb2e.gif)

**Steps to reproduce:**
Use the following code code below to reproduce.

**Related code:**

```
<ion-header>
  <ion-navbar color="navbarColor">

    <ion-title><img class="title-image" src="assets/images/mb-logo-w.png"/></ion-title>
    <ion-buttons end>
      <a class="hidden-sm" ion-button color="light" clear href="index.html">
        Start Over
      </a>
      <a class="hidden-lg" ion-button icon-only color="light" clear href="index.html">
        <ion-icon name="power"></ion-icon>
      </a>
    </ion-buttons>
  </ion-navbar>
</ion-header>
<ion-content>
 <ion-grid>
        <ion-row responsive-sm>
          <ion-col width-50>
            <ion-item>
              <ion-label color="primary" stacked>First Name</ion-label>
              <ion-input  type="text" ></ion-input>
            </ion-item>
          </ion-col>
          <ion-col width-50>
            <ion-item>
              <ion-label color="primary" stacked>First Name</ion-label>
              <ion-input  type="text" ></ion-input>
            </ion-item>
          </ion-col>
        </ion-row>
        <ion-row responsive-sm>
          <ion-col width-50>
            <ion-item>
              <ion-label color="primary" stacked>First Name</ion-label>
              <ion-input  type="text"></ion-input>
            </ion-item>
          </ion-col>
          <ion-col width-50>
            <ion-item>
              <ion-label color="primary" stacked>First Name</ion-label>
              <ion-input  type="text"></ion-input>
            </ion-item>
          </ion-col>
        </ion-row>
        <ion-row responsive-sm>
          <ion-col width-50>
            <ion-item>
              <ion-label color="primary" stacked>First Name</ion-label>
              <ion-input  type="text"></ion-input>
            </ion-item>
          </ion-col>
          <ion-col width-50>
            <ion-item>
              <ion-label color="primary" stacked>First Name</ion-label>
              <ion-input  type="text"></ion-input>
            </ion-item>
          </ion-col>
        </ion-row>
        <ion-row responsive-sm>
          <ion-col width-50>
            <ion-item>
              <ion-label color="primary" stacked>First Name</ion-label>
              <ion-input  type="text" ></ion-input>
            </ion-item>
          </ion-col>
          <ion-col width-50>
            <ion-item>
              <ion-label color="primary" stacked>First Name</ion-label>
              <ion-input  type="text"></ion-input>
            </ion-item>
          </ion-col>
        </ion-row>
        <ion-row responsive-sm>
          <ion-col width-50>
            <ion-item>
              <ion-label color="primary" stacked>First Name</ion-label>
              <ion-input  type="text" ></ion-input>
            </ion-item>
          </ion-col>
          <ion-col width-50>
            <ion-item>
              <ion-label color="primary" stacked>First Name</ion-label>
              <ion-input  type="text" ></ion-input>
            </ion-item>
          </ion-col>
        </ion-row>
      </ion-grid>
</ion-content>
```

**Other information:**
IOS 10.x. I'm not experiencing the issue in the ionic 2.0.0 environment. Only since i've moved to ionic 2.1.0.  I've tried to determine what differences may be present in the generated html, but I do not see any. Ionic-Keyboard plugin is installed with default configuration.

FYI: The issue doesn't occur after rolling back to "ionic-angular": "2.0.0" and "@ionic/app-scripts": "1.0.0"
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002

```

**Comment by AmitMY** [comment]
I'm having the same problem on Android. Post on forum: https://forum.ionicframework.com/t/android-keyboard-is-over-the-input-doesnt-scroll-to-input/81450

(There is no new info there, just to show the problem occurs and to supply another buggy case)

**Comment by mikelunn** [comment]
@AmitMY I also posted a question to the forum, as well as the slack channel. I was able to get the markup to function as expected by rolling back dependencies to "ionic-angular": "2.0.0" and "@ionic/app-scripts": "1.0.0"

**Comment by brunomrpx** [comment]
Hi guys. I solved the problem adding the style```position: initial``` to ```ion-col``` elements. It seems that ```ion-col```has ```position: relative``` and on input focus, the scroll is based on the [```offsetTop```](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetTop)  that is relative to the top of the [```offsetParent```](https://developer.mozilla.org/en-US/docs/Web/API/HTMLelement/offsetParent) node - ```ion-col``` in this case. I think that removing [```this line```](https://github.com/driftyco/ionic/blob/master/src/components/grid/grid.mixins.scss#L98) also solve the problem, but I don't know if it doesn't break something.

**Comment by AmitMY** [comment]
@brunomrpx Thanks! Solved for me also.

**Comment by mikelunn** [comment]
@brunomrpx Thanks. Setting position to initial for ion-col elements fixed the scroll issue for me as well. I'm not sure what course of action should be taken at this point. Since this was working in the 2.0.0 release, i'll leave the issue open. Thanks for your help.

**Comment by dylanvdmerwe** [comment]
Note that this is still an issue with release 3.1.0.

**Comment by manucorporat** [comment]
Keyboard is a big priority for us, but understand this is complicated. Fortunately I think all issues will be fixed here: https://github.com/driftyco/ionic/pull/11401/files

+ some native assistance in the latest WK plugin

**Comment by lfitzgerald** [comment]
@manucorporat Do you know when 11401 will be in a release?

**Comment by MikeMijnheer** [comment]
Setting position to initial for ion-col elements worked also for me, few weeks ago.. but now it doesn't anymore (it's been some time since I last tested this). Anyone else has the same?

**Comment by mikelunn** [comment]
@MikeMijnheer What changed? Did you upgrade your ionic version?

**Comment by MikeMijnheer** [comment]
Tbh, Ik cannot think of anything that changed, Ik didnt upgrade anything. I still have version 2.2.0.

**Comment by lpsantana** [comment]
Any solution on this?

**Comment by viveksinha9** [comment]
Any update on this? Having same problem.

**Comment by Nightmarepg** [comment]
Im also facing this issue with Android.

**Comment by MikeMijnheer** [comment]
I could solve this by adding "scrollAssist: true" and "autoFocusAssist: true" to app.module in the `@ngModule`. Like this: 
`imports: [
    IonicModule.forRoot(MyApp, {
      scrollAssist: true,
      autoFocusAssist: true
    })
],`

**Comment by viveksinha9** [comment]
@MikeMijnheer It's not working. I solved this problem in iOS using .input-cover{position: static}. But problem still persist in android.

**Comment by ddoerr** [comment]
+1 This is critical for our project.

**Comment by annayafi** [comment]
same problem for me. Thanks to @brunomrpx it works now, but last grid row still can't really show up, even if everything is pushed up, there would need a few pixels more. Thanks a lot for your answer

**Comment by RomanSaronov** [comment]
Same problem. Waiting for solution. Thanx

**Comment by digaus** [comment]
Still having the issue... first col works fine but all others not... suggested solutions did not work on Android.

**Comment by ekhmoi** [comment]
Any update on this one?

**Comment by chillyprig** [comment]
Did you guys try this:
https://github.com/ionic-team/ionic/commit/1fe1c1e291b8633dbaf34f4409b5b22bde19b109

for me it worked for iOS

**Comment by nosTa1337** [comment]
Got the same issue. Any solutions for android?

**Comment by cgrall4cloud** [comment]
Same Issue.

**Comment by pthorp** [comment]
@viveksinha9
Using `.input-cover{position: static}` resolved my problem with this issue too.

**Comment by PrateekChitransh** [comment]
.col {
    position : initial !important;
}

in app.scss worked for me. Thanks.

**Comment by daveshirman** [comment]
@adamdbradley 

Why is this still an open issue? This is ridiculous!  

We know you're all working super hard and appreciate it, but this is such a basic piece of functionality for the framework that needs to be prioritised over offering cloud services and PWAs etc.

I've got similar outstanding tickets with no reply and they're just as fundamental.  People will start abandoning your platform for React Native or NativeScript or A.N.Other framework if basic functionality like this isn't right.  It's crucial to apps being usable and marketable.

Please advise. Thanks.

**Comment by nosTa1337** [comment]
I totally agree with @daveshirman 

My problem from 26th july still exists.

**Comment by TomCosta** [comment]
I **solved** it just adding a code to app.scss
`.scroll-content {
padding-bottom: 0!important;
}`

**Comment by phantoxe** [comment]
@TomCosta u just put this code in app.scss e nothing more?

**Comment by TomCosta** [comment]
@phantoxe Also you can change the Android Manifest, if it's necessary...
`<activity android:windowSoftInputMode="adjustPan|adjustResize"> </activity>`

**Comment by nosTa1337** [comment]
@TomCosta this shouldn't be fixed in the android manifest, this should be fixed in the ionic core...

**Comment by nosTa1337** [comment]
@TomCosta Sure. Wasn't meant to be offending ;). All fixes are welcome but I didn't manage to make mine work yet.

**Comment by SquallX** [comment]
Need solution, please.

**Comment by nosTa1337** [comment]
would be awesome :)

**Comment by phantoxe** [comment]
@SquallX it is very simple... your input is inside of a COLUMN? Remove the ION-COL and put your field inside a DIV... :-( It is a bug in IONIC 3... All elements inside a ION-COL have this problem... :-(

**Comment by nosTa1337** [comment]
I did some research in the core files...

https://github.com/ionic-team/ionic/blob/b1803510e32eff112ee94c3292d06377f74e4d89/src/components/input/input.ts

This is the file which controls the scrolling of the input.

I guess the problem starting in line 487:  
ele = <HTMLElement>ele.closest('ion-item,[ion-item]') || ele;
return this._scrollData = getScrollData(
      ele.offsetTop, ele.offsetHeight,
      this._content.getContentDimensions(), this._keyboardHeight, this._plt.height());
  }

When I tried to get the offset for several example everytime I put the input in the col it shows me the following output:

![2017-10-20 12_56_39-aufgabe 483](https://user-images.githubusercontent.com/13113717/31817891-29a84fd6-b596-11e7-9e39-313b3e2ef26f.png)

`<ion-grid>
      <ion-row>
        <ion-col>
          <ion-item>
            <ion-label floating>test</ion-label>
            <ion-input type="text" #testinput4></ion-input>
          </ion-item>
        </ion-col>
      </ion-row>
    </ion-grid>`

This is the structure of the output.

If i remove the grid it looks like this:

![2017-10-20 12_57_34-aufgabe 483](https://user-images.githubusercontent.com/13113717/31817926-51c02a48-b596-11e7-8668-9f2fc4c70caf.png)

So somwhere is a line missing where the correct position of the item is set...

**Comment by SquallX** [comment]
@phantoxe Yes but why it works perfectly with iOS and not with Android ? It's not logic...

**Comment by SquallX** [comment]
Also,

Without ion-grid it does not works...
```


<ion-header>
  <ion-navbar>
    <ion-buttons end>
      <button ion-button icon-only (click)="closeLogin()">
        <ion-icon name="close"></ion-icon>
      </button>
    </ion-buttons>
  </ion-navbar>
</ion-header>

<ion-content class="transparent-header" [ngStyle]="{'background-image': 'url(assets/imgs/backgrounds/bg_connexion.jpg)'}">
  <div padding>
    <img class="logo" src="assets/imgs/design/logo.png" />
    <form [formGroup]="loginData" (ngSubmit)="login()">
      <ion-list inset class="no-border">
        <ion-item>
          <ion-input type="email" formControlName="email" placeholder="Votre adresse email..."></ion-input>
        </ion-item>
        <ion-item>
          <ion-input type="password" formControlName="password" placeholder="Votre mot de passe..."></ion-input>
        </ion-item>
      </ion-list>
      <div class="auth-buttons">
        <ul>
          <li><span (click)="goToSignUp()">Je n'ai pas de compte</span></li>
          <li><span (click)="goToRecover()">J'ai oublié mon mot de passe</span></li>
        </ul>

        <button ion-button class="login-button" [disabled]="!loginData.valid">Connexion</button>
      </div>
    </form>
  </div>
</ion-content>
```

**Comment by ATakaSKY** [comment]
I am also stuck. Any updates Ionic champs.

**Comment by camicase82** [comment]
I just tested @TomCosta solution .scroll-content { padding-bottom: 0!important; } and its working with ionic-angular 3.7.1

**Comment by nosTa1337** [comment]
So how it's going? any updates @IonicTeam ?

**Comment by teejaydub** [comment]
This affected me too - after an hour of trying various fixes from variants of this ticket, `.scroll-content { padding-bottom: 0!important; }` worked. It seems like this basically affects most simple forms within an `ion-slides` component, so it seems pretty important, though maybe I'm wrong.

**Comment by krunal9421** [comment]
In my case I am using form into modal and into the footer of modal there are buttons. when I click on text field to write and keyboard opens up then scroll get limited. The text field get overlay behind keyboard. Please help I am stuck from weeks in this case.

**Comment by thomasvht** [comment]
I have the same issue as krunal9421. I have an input modal with checkboxes and a textarea. When i click in the textarea (that is the last element before the buttons), the keyboard is positioned above the textarea and i can't see why i'm typing. I've been searching a solution for days now.

**Comment by krunal9421** [comment]
@thomasvht you can try out for focus on element of using click event on last text field or you can use scroll top to view. You just need to remove bottom padding on last text field and add scroll top, This may help you.
Mine case is different, I using slides into modal with footer button. In one of the slide there is form which creating this problem. Waiting for the solution.
Thank you.

**Comment by hoisel** [comment]
I have same issue as @krunal9421

**Comment by amarewgs** [comment]
same same here, it seems it will stop scrolling to a limit. @ionicteam any updates? this is not good at all, BTW there is no issue with ios with this.

<ion-header>
  <ion-navbar>
    <ion-buttons left>
      <button ion-button menuToggle>
        <img alt="logo" height="30" src="assets/imgs/mela-logo.png">
      </button>
    </ion-buttons>
    <ion-title>
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content no-scroll overflow-scroll="false" has-bouncing="false" scroll="false" padding>

  <ion-scroll has-bouncing="false" style="width:100%;height:100%;" scrollY="true">

    <div class="main-content">
      <p>Registering for an account will allow you to use any one of our applications using the same email/password
        combination.</p>

      <ion-list>

        <ion-item>
          <ion-label floating>First Name</ion-label>
          <ion-input [(ngModel)]='user.firstName'></ion-input>
        </ion-item>

        <ion-item>
          <ion-label floating>Last Name</ion-label>
          <ion-input [(ngModel)]='user.lastName'></ion-input>
        </ion-item>

        <ion-item>
          <ion-label floating>Email</ion-label>
          <ion-input [(ngModel)]='user.email' type="email" required="true" pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,6})+$"></ion-input>
        </ion-item>

        <ion-item>
          <ion-label floating>Password</ion-label>
          <ion-input [(ngModel)]='user.password' type="password"></ion-input>
        </ion-item>

        <ion-item>
          <ion-label floating>Password Again</ion-label>
          <ion-input [(ngModel)]='user.confirmPassword' type="password"></ion-input>
        </ion-item>

        <ion-item>
          <ion-label>By clicking signup you agree to Terms and Conditions</ion-label>
          <ion-checkbox [(ngModel)]="termsConditions"></ion-checkbox>
        </ion-item>

      </ion-list>

      <button class="register" ion-button [disabled]="!termsConditions" type='submit' full color="primary" (click)='submitRegistration()'>Register
      </button>
    </div>
  </ion-scroll>
</ion-content>

**Comment by eherve** [comment]
I have the same issue on ios, on first focus the keyboard does not push up the view.
But if I click on the action "next input" on the keyboard, the view is pushed up if the field was hidden by the keyboard.

**Comment by FredeHo** [comment]
@brunomrpx Worked like a charm. Every issue we had with the scrolling/focus magically disappeared. Thanks a lot <3

**Comment by chaitanya-nyros** [comment]
@brunomrpx  Super cool its work like a charm :)

**Comment by jeffminsungkim** [comment]
Any solutions guys? None of them are working for me. :(

**Comment by narendra-ct** [comment]
any one solved this issue in ios @nosTa1337 i am still facing same issue if you have resolved this issue please post it here

**Comment by nosTa1337** [comment]
@narendra-ct I have only deployed it to android and still not working. hoping for a fix from the ionic team :)

**Comment by daveshirman** [comment]
Haha, a fix from the Ionic team! Good one :)

Look at how many tickets I've got open for up to a year that are simple
with no reply at all. SIGH.

**Comment by jhitchcock** [comment]
How has this been a bug since march? fields being hidden by keyboard.. basic

**Comment by dsgriffin** [comment]
Bruno's solution + an `!important` resolves the issue for me:

```
ion-col {
    position: initial !important;
}
```

**Comment by jwieneke** [comment]
@dsgriffin 's solution is working for me.
But only if user sets focus to the input. If I set focus to an input programatically keyboard still hides the field. Has anybody a solution for this issue too?

**Comment by manikandan07081995** [comment]
i need virtual keyboard on kiosk mode some one help me

**Comment by iamongit** [comment]
After wasting an hour and going through a couple dozen related issues this is what finally worked for me, I'm using the latest ionic. 

`ion-col {
    position: initial !important;
}`
Keyboard scrolling/not-scrolling and bouncing content around is a mess with ionic apps, so many open issues linked to each other and no definitive solution.
Thanks @brunomrpx

**Comment by aslaugsollilja** [comment]
any news on this? None of the suggested solutions work for me... the problem is on android, IOS works fine

**Comment by nosTa1337** [comment]
As there haven't been a working solution for my special case I did the positioning by myself. Isn't that nice but better than a hidden input field behind the keyboard.

````
@ViewChild(Content) content: Content;
//fix the scrolling until ionic has fixed it ...
private scrollTo(elementId: string, delay?: number)
{
        if (!delay)
            delay = 0;

        setTimeout(() =>
        {
            let yOffset = 0;
            let element;

            if (elementId !== null)
            {
                element = document.getElementById(elementId);

                if (elementId.startsWith('serial'))
                {
                    yOffset = element.offsetTop + element.parentElement.parentElement.parentElement.parentElement.offsetTop - 40;
                } else if (elementId.startsWith('identified') || elementId.startsWith('location'))
                {
                    yOffset = element.parentElement.offsetTop + element.parentElement.parentElement.parentElement.parentElement.offsetTop - 10;
                }
            }

            this.content.scrollTo(0, yOffset, 750);
        }, delay);
}
````

In the HTML assign the id to the highest ion-item.

````
<ion-item id="location">
....
<ion-input (ionFocus)="scrollTo('location')"....>
...
</ion-item>
````

**Comment by NagarajVenkatesan** [comment]
<ion-input type="text" name="username" [(ngModel)]="model.username" (ionFocus)="myfunction();" required></ion-input>

-------------------------------------------------

import { Content } from 'ionic-angular';


@ViewChild(Content) content: Content;


myfunction(){
	this.content.scrollTo(0,200);
}

**Comment by Alex0x47** [comment]
Thanks to @NagarajVenkatesan and some research, I found a solution for iOS and Android.

**- iOs :**
In app.module.ts :
```
imports: [
    [...]
    IonicModule.forRoot(MyApp, {
      platforms:{
        ios:{
          scrollAssist: false,
          autoFocusAssist: false
        }
      }
    }),
   [...]
  ]
```
That's all.

**- Android :**
In my view :

`<ion-textarea (ionFocus)="fixScroll()" id="absence-textarea"></ion-textarea>`

.ts file :

```
fixScroll(){
    if(this.device.platform == "Android"){
      setTimeout(() => {
        let element = document.getElementById("absence-textarea");
        let box = element.getBoundingClientRect();
        let top = Math.round(box.top*10);
        this.content.scrollTo(0, top, 100);
      }, 350);
    }
  }
```

I use a timeout so the keyboard is active when the code is executed. Obviously the "box.top" value depends on your HTML structure. It looks like, for me, that 10 times the difference between the top of my element and the top of the view (when the keyboard is active) sets the element at a right place. I'll have to do more tests but for now, it's the best solution I found.

**Comment by hiepxanh** [comment]
this issue, should not be exist after 1 year, it was 1 year.

**Comment by centogram** [comment]
This placed in my app.scss resolves the problem for me
```
ion-col {
  position: initial !important;
}

```

**Comment by felipegouveiae** [comment]
@adamdbradley  @brandyscarney  @manucorporat 

Is there any news about that? Can someone from Ionic Team advise?

**Comment by daveshirman** [comment]
The Ionic team have very plainly stated they're not releasing any fixes for
the current ionic version and instead focusing on a new release.

There is no point wasting time waiting for a fix on existing issues. Find a
workaround.

Quite a shame but that's the reality.

**Comment by felipegouveiae** [comment]
@daveshirman this is quite disappointing not to say unacceptable. 

We're using the latest version. Ionic 3. Instead of creating new versions that as a consequence of this type of answer no one would bother to use, your company may should pay attention to retaining existing customers. 

I have an Ionic Pro Developer Customer and I have 3 apps on Ionic in the last 3 months and the Ionic Team just turn its backs on us?

In several situations, I defended Ionic over Reactive Native to get a stupid answer like that. 

No cool at all. 

@adamdbradley @brandyscarney @manucorporat

**Comment by mhartington** [comment]
@felipegouveiae We have not turned our back on you.

We've been working on the 4.0 version of Ionic which contains a lot of bug fixes and improvements to the overall framework. This issue is closed as it's been fixed in the next major release.

**Comment by brandyscarney** [comment]
I just want to chime in here. We realize it looks like we haven't been fixing issues or possibly doing much of anything because of the lack of responses on issues. The framework team is a small team - there are currently 9 of us on the framework (which includes the CLI, documentation, Stencil & more). We have a meeting every Monday morning to discuss our week, and we update our public [Ionic Framework Meeting notes](https://docs.google.com/document/d/1LrPDUkfXpqPIsghaSCxHyN1GIZ0TK2bwFxOZx2GKWtI/edit?usp=sharing) so others can see what we're focused on. While we could spend more time responding to issues, this would mean we are spending less time making code fixes. In order to fix a lot of the underlying issues, we made the decision to put all of our focus into the next version.

Why did we decide to go all in on the next major version? We have spent a lot of our time keeping the framework up-to-date with each release of Angular, trying to decrease startup times, and working on build scripts. The more time we spent on all of this, the less time we had to spend on improving and adding components. In order to solve this, we decided to test out migrating our internal components to use web components. We ended up building a web component compiler called [Stencil](https://stenciljs.com/) to make it easier for us to create standards-based web components. What we found is that web components introduce a lot of benefits for both us as open source maintainers and you as an Ionic developer. With the switch to use web components internally startup times have decreased, less code is being shipped, many issues are being fixed indirectly, we are moving towards web standards, we're seeing performance gains that are aligned with Google's requirements for PWAs, we have decoupled ourselves from Angular releases (which means you don't have to wait on us to update!), we've switched to using Angular's tools and we have gained the ability to support multiple frameworks.

I want to clarify that adding support for multiple frameworks does not mean we don't still love or support Angular. We are first and foremost supporting Angular, so much so that we have added support for their router and CLI. We're working hard to make the migration as smooth as possible. We recently released a `4.0.0-alpha.0` of `@ionic/angular` and have so far received a lot of constructive & positive feedback. Hopefully we will have a beta out soon, and with it a blog post with steps to upgrade. Thank you for your understanding.

**Comment by renanrlp** [comment]
Thanks to @Alex0x47! Great solution! In iOS it worked beautifully, but, for me, in Android, the problem persists... 
Would anyone have an idea of what might be happening?

**Comment by Stephane84** [comment]
I also had issues with the keyboard (cordova-plugin-ionic-keyboard) in ionic3.
Not in grid, but simply in a form with ion-list and ion-item of input
The keyboard was scrolling over the clicked input.
I solved it by : 
putting in config.xml :
`<preference name="KeyboardResizeMode" value="ionic" />`

putting in app.module.ts :
```
IonicModule.forRoot(MyApp, {
    scrollPadding: false,
    scrollAssist: false,
    autoFocusAssist: false,
)}
```

putting in the constructor of app.components.ts :
```
window.addEventListener("keyboardDidShow", () => {
    document.activeElement.scrollIntoView(false);
});
```

Then, when we click an input, we catch the event fired when the keyboard is shown, and, use js function scrollIntoView on the focused element, to make it visible in the DOM by scrolling the content.

scrollIntoView can be align to top of scroll-content or at the bottom with the keyboard.

You can also try to add margin top or bottom at the input by scrolling many px :

```
window.addEventListener("keyboardDidShow", () => {
    document.activeElement.scrollIntoView(false);
    
    const elem: HTMLCollectionOf<Element> = document.getElementsByClassName("scroll-content"); // The last content shown, so the current page
    if (elem !== undefined && elem.length > 0) {
        elem[elem.length - 1].scrollTop += 40; // add 40px between the keyboard and the input
    }

});
```

**Comment by Nytsee** [comment]
Hey everyone, i've been struggling with this issue for a long time and this line solved it 👍 
 page-chat{
     .scroll-content{
         margin-top:50px !important; // the value should be the exacte ion-header height !
     }
 }

**Comment by hiepxanh** [comment]
Ithank you @Nytsee y

**Comment by maikonigor** [comment]
the solution proposed by @brunomrpx  worked fine for me!

Obrigado cara! Se eu tivesse perto de ti, te pagava uma cerveja!

**Comment by atheerahassan** [comment]
none of the answers worked for me when I run ionic serve -l. everything just seems to be perfectly fine when I generate it in apk..

**Comment by jp-TFIT** [comment]
@Alex0x47 thanks for your approach! Additionally to your solution I have to add the following line to the app.component.ts

`        this.keyboard.didShow.subscribe(() =>{
          document.activeElement.scrollIntoView(false)
        })
`

keyboard is an instance of Keyboard from '@ionic-angular'

**Comment by MrDrProfX** [comment]
Yep, I'm able to solve this by using css coupled with ngClass:
SCSS
`.focused-content {
    .scroll-content, .fixed-content {
        margin-top: 140px !important;
        margin-bottom: 128px !important;
    }
}`
HTML
`<ion-content [ngClass]="{'focused-content': isFocused()}">
<textarea #myTextArea></textarea>
</ion-content>`
TS
`isFocused() {
    return document.activeElement === this.myTextArea.nativeElement;
  }`

**Comment by MrDrProfX** [comment]
Here's a directive you can slap on to any div container which will auto adjust the marginBottom to account for the keyboard size:

(don't use it on ion-content, that wont work, use it on a div or other normal containers)

```
import { Directive, ElementRef } from '@angular/core';
import { Keyboard } from '@ionic-native/keyboard';

@Directive({
  selector: '[move-up-with-keyboard]' // Attribute selector
})
export class MoveUpWithKeyboardDirective {

  constructor(private keyboard: Keyboard, private elementRef: ElementRef) {}

  ngAfterViewInit() {
    this.keyboard.onKeyboardShow().subscribe(event => {
      this.elementRef.nativeElement.style.marginBottom = event.keyboardHeight + 'px';
    });
    this.keyboard.onKeyboardHide().subscribe(event => {
      this.elementRef.nativeElement.style.marginBottom = '0px';
    });
  }
}
```

**Comment by AniciusM** [comment]
@Alex0x47 Best solution i found thanks a lot man
