### ISSUE TITLE
VirtualScroll Can't read property length of null

### ISSUE THREAD

**Issue by aggarwalankush** [ionic-team/ionic#11439]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I got Null exception at https://github.com/driftyco/ionic/blob/master/src/components/virtual-scroll/virtual-scroll.ts#L601

**Expected behavior:**
Check for null before calling length function

**Steps to reproduce:**

Don't know how to reproduce. Got it only a few times.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.3.2 Build version 8E2002

```

**Comment by manucorporat** [comment]
this._nodes never gets the null during runtime, can you provide some source code that reproduces the issue?

**Comment by aggarwalankush** [comment]
Happened few times only. Don't know how to reproduce. Closing this as there are other important issues than this one.

**Comment by ADCJustinH** [comment]
This happens for me after upgrading to ionic 3. 

> Closing this as there are other important issues than this one.

Issues can be prioritized I don't think you should have closed this just because other issues exist...
```
filteredCourses: ICourseResult[];
ngOnInit() {
        this.cSrv.getNearbyCourses(this.nearbyCount)
            .first().subscribe(courses => {
                this.filteredCourses = courses;
            });
    }
```

` <ion-list [virtualScroll]="filteredCourses" approxItemHeight="85px">`

gets the exception every time for me. It happens If I change this around to use the async pipe too. The only fix is to change the first line to:
`  filteredCourses: ICourseResult[]=[]; `

which is not a great solution because I don't know how many times this pattern is used in my app and I'll probably miss one or two :/

**Comment by manucorporat** [comment]
@ADCJustinH I think you have a different issue, this time: `this._nodes` is null.
Which version are you using? make sure you update to 3.1.1

**Comment by ADCJustinH** [comment]
Thanks for taking a look. I am indeed using 3.1.1 but the stack is slightly different:

```
> virtual-scroll.js:535 Uncaught TypeError: Cannot read property 'length' of undefined
>     at VirtualScroll._stepDOMWrite (virtual-scroll.js:535)
>     at virtual-scroll.js:496
>     at dispatch (dom-controller.js:214)
>     at DomController._flush (dom-controller.js:158)
>     at rafCallback (dom-controller.js:147)
```

```
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.0
Xcode version: Not installed
```

and yes, the C in cordova is missing in the console output lol

**Comment by aggarwalankush** [comment]
@manucorporat I am getting the similar error again but now for set property.
```
TypeError: Cannot set property 'length' of null
      at VirtualScroll.readUpdate (....
```

**Comment by Microsmsm** [comment]
I have the same problem after updating ionic to version '3.2.0' anyone can help?

**Comment by pantonis** [comment]
same here. I get:

````
Cannot read property 'length' of null
    at VirtualScroll._stepDOMWrite (virtual-scroll.js:591)
    at virtual-scroll.js:551
    at dispatch (dom-controller.js:214)
    at DomController._flush (dom-controller.js:158)
    at rafCallback (dom-controller.js:147)
````

**Comment by pantonis** [comment]
@ADCJustinH Tried your workaround to change filteredCourses: ICourseResult[]=[]; but doesnt work either.

**Comment by mnewmedia** [comment]
Here are my tests using 3.4.2

### works
- **Init** with empty array works
- **update** array to be empty, works. `this.items.splice(0,this.items.length)`
- **replace** array with new array works.

### fails
- **Init** with undefined gives: `Cannot read property 'length' of null at VirtualScroll._stepDOMWrite`
- **replace** array with empty array, gives no error, but all previous rendered items will still be visible, although they should get destroyed.
- Using virtualScroll inside a `*ngIf="items"`. It will never show up.

### other libs, we can may use
- https://github.com/rintoj/angular2-virtual-scroll (there if data changes you must provide a new array, not updated)
- https://github.com/dinony/od-virtualscroll (everything is an observable)

**Comment by viveksinha121** [comment]
Getting this issue too. Tried this:

	`public hotelsarray: any[] = [];`

```
<ion-list [virtualScroll]="hotelsarray" approxItemHeight="50px">
      <div tappable ion-item *virtualItem="let hotel" class="item-inner-hotel" (click)="hotelClicked(hotel)">
```

**Comment by Kevin-Hamilton** [comment]
@manucorporat I believe the source of this particular bug is a race condition between requestAnimationFrame and ngOnDestroy.  

ngOnDestroy nulls out _nodes, _cells, _date, etc. at https://github.com/ionic-team/ionic/blob/master/src/components/virtual-scroll/virtual-scroll.ts#L819 but there are scheduled raf calls in renderVirtual and in _dom.read() / _dom.write() which might execute after ngOnDestroy has free'd those object properties.

**Comment by danielcrk** [comment]
Getting this as well. Has anyone found a workaround?

**Comment by manucorporat** [comment]
fixed! https://github.com/ionic-team/ionic/commit/88b2e8316dad5c504695405fa2199aacbea5b5d6

**Comment by Kevin-Hamilton** [comment]
I'm not so sure that commit fixes this bug.

I still see the exact same use of, for example, data.topCell being accessed here: https://github.com/ionic-team/ionic/blob/88b2e8316dad5c504695405fa2199aacbea5b5d6/src/components/virtual-scroll/virtual-scroll.ts#L552 without any prior checks to verify data is not null.  And I still see data being set to null here: https://github.com/ionic-team/ionic/blob/88b2e8316dad5c504695405fa2199aacbea5b5d6/src/components/virtual-scroll/virtual-scroll.ts#L820 without cancelling the scheduled requestAnimationFrame that wraps the aforementioned access of data.topCell.

Maybe I'm missing something.  @masimplo which of your code changes did you think addressed this bug?

**Comment by masimplo** [comment]
@Kevin-Hamilton I will have to check and get back to you as I can't remember from the top of my head. I do remember that this error was triggered in a couple situations, maybe yours is different. Are you starting with a null collection or nulling the collection at some other point?

**Comment by pavini** [comment]
I´m getting the same error "VirtualScroll Can't read property length of null"
Ionic 3.13.2

No resolution for this bug?

**Comment by masimplo** [comment]
@pavini this PR will probably be solving your issue. https://github.com/ionic-team/ionic/pull/13107

**Comment by UnderTheMoonspell** [comment]
I'm getting this error with just  a simple test array:

**home-container.html**
`<ion-list [virtualScroll]="testArray" approxItemHeight="'100px'">
    <ion-item *virtualItem="let test">
        {{article.title}}
    </ion-item>
</ion-list>`

**home-container.ts**
`export class HomeContainer {

    testArray = [{title:'a'}, {title: 'b'}];
    constructor() {
    }
}`

In this same home-container I am using an input array (received from an Observable<Array> from the parent container) and it works normally with *ngFor. With virtualScroll not even that simple testArray works.

**Comment by suryabhanbarai** [comment]
Assign array like:-
public items: any[] = [];
will fix the issue.

**Comment by UnderTheMoonspell** [comment]
@suryabhanbarai  it didn't.

The only element inside ion-list is 

`<div class="virtual-last"></div>`

**Comment by chrifrachid** [comment]
**I NEED HELP PLEASE!**

I am loading data from .json file:
![provider ts](https://user-images.githubusercontent.com/16919684/39674305-c9b5f5a4-5141-11e8-861c-3096f9d94c1b.jpg)

This is home.ts file
![home ts](https://user-images.githubusercontent.com/16919684/39674311-d564ec98-5141-11e8-9dab-3e3c5e9e8964.jpg)


and here is the home.html file
![home html](https://user-images.githubusercontent.com/16919684/39674318-e09e08f6-5141-11e8-94fa-a21b08320e12.jpg)


The error 
![error](https://user-images.githubusercontent.com/16919684/39674324-ec04c20c-5141-11e8-82ab-5c582a7ffff5.jpg)
