### ISSUE TITLE
Ionic 3 app showing additional area below status bar iOS 11.0 beta

### ISSUE THREAD

**Issue by hofimax** [ionic-team/ionic#12011]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic 3 App on iOS 11.0 beta (version 15A5278f) (simulator) shows additional unneccesary white area under status bar:

![a1](https://user-images.githubusercontent.com/2486593/27014624-01745604-4efd-11e7-8361-a4386b0101a6.PNG)

This can be fixed by adding "viewport-fit=cover" to the viewport meta tag, but introduces new problem at bottom of screen:

![a2](https://user-images.githubusercontent.com/2486593/27014647-4b744af2-4efd-11e7-9d8f-6d523982bf5a.PNG)

**Expected behavior:**
Look the same as in iOS 9 and iOS 10

**Steps to reproduce:**
Run Ionic 3 app in iOS 11 simulator using xCode 9 beta

**Comment by mhartington** [comment]
Hey there! So we're going to keep all the ios 11 issues in a related issue (#12020) in order to better track any issue that comes up during the betas. I've added your issue and information there. Please follow #12020 for any updates.

**Comment by hofimax** [comment]
this issue has been resolved as of ios 11 beta 5

**Comment by abbazer** [comment]
@hofimax I’m using iOS 11 beta 9 but this problem still appear

**Comment by hofimax** [comment]
@abbazer not for me, but we are using the WKWebView

**Comment by abbazer** [comment]
Solved by adding 
<meta name="viewport" content="viewport-fit=cover, initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">

**Comment by hofimax** [comment]
Just tested on iOS 11 beta 10 with WKWebView and it works reliably. We are NOT using viewport-fit=cover

**Comment by ahmadtawakol** [comment]
If I don't add `viewport-fit=cover` then the header doesn't go under the status bar and the status bar just has a white background. If I add `viewport-fit=cover` then the header goes under the status bar like it should, but it's as if the whole app moves up, instead of stretching to fill the screen, and the white background that was under the status bar is now under the footer of the app.

I'm not sure if I'm explaining it clearly, let me know if you need me to clarify anything.

**Comment by tobiasmuecksch** [comment]
Problem still exists in iOS 11 Golden Master. This is NOT a beta only problem and will NOT go away when iOS 11 is released in the next few days.

**Comment by mhartington** [comment]
We're working with the cordova team to address this. Please keep an eye out on this.

https://github.com/apache/cordova-plugin-statusbar/pull/85

**Comment by jacquesdev** [comment]
For what it's worth I see it as well in ionic1, assuming because it's related to `cordova-plugin-statusbar.`

**Comment by dimitri320** [comment]
In my case, when I added `viewport-fit=cover` my whole app just shows a blank white screen and nothing else. So it makes things every worse for me. Anyone experiencing similar behaviour?

**Comment by mhartington** [comment]
@dimitri320 can you open a new issue instead and provide a minimal demo in a github repo? Have not seen that before

**Comment by dimitri320** [comment]
@mhartington I've started a new issue at https://github.com/ionic-team/ionic/issues/13208. I've setup a brand new project, and it works just fine, so couldn't really replicate a new github repo as an example, as a new project works ok, but my old one (I started it about 7-8 months ago with Ionic 2) doesn't. Anything else I can provide to help the search?

Many thanks!

**Comment by glemiere** [comment]
Any news here ?

**Comment by mhartington** [comment]
@glemiere the issue has been solved. Please review the thread and make any updates. If there’s is still an issue after that, please open a new issue.

**Comment by glemiere** [comment]
@mhartington adding "viewport-fit=cover" to my index.html worked for me ;-)

**Comment by lovelyelfpop** [comment]
White bottom bar only appears on ios11 when using [cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine) and latest [cordova-plugin-statusbar](https://github.com/apache/cordova-plugin-statusbar)

**Comment by glemiere** [comment]
@lovelyelfpop did you try using adding this to your index.html ?
  <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

**Comment by lovelyelfpop** [comment]
@glemiere `viewport-fit=cover` is the default behavior for [cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine)

**Comment by lovelyelfpop** [comment]
About the bottom space when using wkwebview, here is a workaround:

Add some code in `cordova-plugin-wkwebview-engine\src\ios\CDVWKWebViewEngine.m`, 
```
// re-create WKWebView, since we need to update configuration
WKWebView* wkWebView = [[WKWebView alloc] initWithFrame:self.engineWebView.frame configuration:configuration];
//add begin
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000
if (@available(iOS 11.0, *)) {
  [wkWebView.scrollView setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];
}
#endif
//add end
wkWebView.UIDelegate = self.uiDelegate;
self.engineWebView = wkWebView;
```

The code above came from [cordova-plugin-ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview)

**Comment by laberg** [comment]
simply adding the cordova-plugin-ionic-webview fixed it for me!
