### ISSUE TITLE
NgModuleLoader not Webpack-friendly

### ISSUE THREAD

**Issue by sinedied** [ionic-team/ionic#12285]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When trying to build a Angular app using `ionic-angular` without the Ionic CLI but with webpack (using `angular-cli` for example), this warnings appear during build:
```bash
WARNING in ./~/ionic-angular/util/ng-module-loader.js
54:11-36 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ionic-angular/util/ng-module-loader.js
69:11-36 Critical dependency: the request of a dependency is an expression
```
These are due to the dynamic `System.import()` making Webpack unable to alias properly the files to import statically.

**Expected behavior:**
It should build without warnings.

**Steps to reproduce:**
Create a new project with `angular-cli`, then `npm install -S ionic-angular` and include `ionic-angular` modules in `app.module.ts`.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Ionic CLI               : 3.4.0

System:

    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.4 
    npm        : 4.2.0 
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by sinedied** [comment]
@jgw96 This is not a support question but indeed a bug report.
According to the source of the issue (ie webpack): https://github.com/webpack/webpack/issues/196 which explains why this warning is emitted, there is no other way to fix this warning other than fixing the library causing this.

**Comment by sinedied** [comment]
After investigation and according to the docs, this can be resolved with [require context](https://webpack.github.io/docs/context.html#require-context).

@jgw96 Are you open to a PR on this?

**Comment by sharanainapurapu** [comment]
@sinedied I am facing same issue. Can you please explain little in detail what you mean by "resolved with require context"

**Comment by sinedied** [comment]
I did not fix the issue and went with the (harmless) warning since I want to keep a vanilla angular-cli setup. However if you eject your webpack configuration, you can either ignore it or use a require context setup to silence the warning.

**Comment by FazioNico** [comment]
Same issu.. hope  @ionic-team will fix it soon as possible to realy enable Ionic UI on a simple standard Angular CLI project.
