### ISSUE TITLE
Fist tabs is always selected even if we use lazy load @IonicPage

### ISSUE THREAD

**Issue by 5im0n** [ionic-team/ionic#12304]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I have a home page with three tabs. I do not set the attribute `selectedIndex` so the first tab is selected as default. My three pages are lazy loaded, I set the decorator `@IonicPage` for each of them, with a custom segment.
When I press `F5` to reload the page, even if I was on the third tab, the first will be always selected. The lazy load don't care about url segment.

**Expected behavior:**
Depending on the URL you are on, the correct tab should be selected, not the first as default.

**Related code:**

*Weather page*
```
@IonicPage({
  name: 'WeatherPage',
  segment: 'weather-forecast',
})
```
*Home page*
```
public FavoritesPage = 'FavoritesPage';
public LibraryPage= 'LibraryPage';
public WeatherPage = 'WeatherPage';
```
```
<ion-tab [root]="FavoritesPage" tabTitle="fav" tabIcon="star"></ion-tab>
<ion-tab [root]="LibraryPage" tabTitle="Library" tabIcon="book"></ion-tab>
<ion-tab [root]="WeatherPage" tabTitle="Library" tabIcon="partly-sunny"></ion-tab>
```

**Ionic Info**

Cordova CLI: 6.5.0
Ionic Framework Version: 3.4.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 2.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.3
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind posting your `ionic info` please?

**Comment by 5im0n** [comment]
Done

**Comment by mhartington** [comment]
Can you please test `ionic-angular@3.5.0` this should have been fixed.

**Comment by 5im0n** [comment]
@mhartington, I just test with the version `3.5.0`, but the issue is still here.

1: First tab: `http://localhost:8085/#/nav/n4/machine/2/tabs/t0/favorite/favorite`
2: Second tab: `http://localhost:8085/#/nav/n4/machine/2/tabs/t0/library/library`

When I go to the second tab and I refresh the page `F5`, the first tab is loaded

**Comment by mhartington** [comment]
Please provide a minimal example to debug.

**Comment by 5im0n** [comment]
@mhartington, Humm, it's strange, I test with your repository with Tabs lazy loading https://github.com/mhartington/lazyLoadTabs.git and it seems to works...

My application is much more complex, I'm gonna investigate, if you have some clues

**Comment by mdo7s** [comment]
I have the same issue after I upgraded to 3.6 (I upgraded to get cleaner url with tabs). I was able to refresh with the nightly version 3.5.3-201707242206.
Any luck finding your issue?

**Comment by adamduren** [comment]
I am experiencing this as well with 3.6. I reproduce by starting with the tab template and convert each of the three pages to lazy load by adding a module and decorating with IonicPage. I do the same with the tabs component. Then removing all static imports. Urls seem to update properly but on refresh first tab is always selected.

**Comment by adamduren** [comment]
I switched to `ionic-angular` via `npm install ionic-angular@3.5.3-201707242206` as suggested by @mdo7s with no luck.

**Comment by adamduren** [comment]
I cloned @mhartington's repo `https://github.com/mhartington/lazyLoadTabs.git ` ran `npm install && ionic serve` and observe the same issue of the first tab always being selected on replace.

Here is my `ionic info`:
(Note: I have also tried with ionic@3.6.0 but downgraded it in order to match the repo.)
```
global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts : 1.3.4
    Ionic Framework    : ionic-angular 3.0.1

System:

    Node       : v7.4.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.0
    ios-sim    : 6.0.0
```

**Comment by mdo7s** [comment]
@adamduren this issue only appeared when I followed @danbucholtz instructions to update ionic.
> npm install -g ionic@latest
npm install @ionic/app-scripts@latest --save-dev
npm install ionic-angular@latest --save

if I roll back to my old version from github, everything works again, except I get back this annoying url path "#/nav/n4/tabs/tabs/t0"

**Comment by adamduren** [comment]
@mdo7s I was able to fix this by giving the `ionicPage` decorator on the `TabsPage` a `segment` value other than `tabs`. After that everything worked nicely.

**Comment by 5im0n** [comment]
@adamduren  works for me too, but it sounds very weird...

**Comment by kensodemann** [comment]
I am going to close this based on the workaround that @adamduren posted and also based on the fact that the next major version of Ionic will have large changes made in the navigation area where it will rely on the router of whichever framework is being used, so this should no longer be an issue at all at that point.

**Comment by HugoHeneault** [comment]
For the record, if anyone falls here after searching for a same issue. 
I got the same kind of problem, because I had 2 tabs pointing to the same root (but with different params). 

I changed the way I handle the params to have only one tab and it started ignoring the URL on reload :)
Hope ionic v4 will bring a solid router!
