### ISSUE TITLE
Browser back button with @IonicPage pages throws TypeError: e.done is not a function

### ISSUE THREAD

**Issue by antoineol** [ionic-team/ionic#12499]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x** - 3.6.0

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
If we have 2 pages using `@IonicPage` annotation for deep linking, we navigate from Page 1 to Page 2 and click the browser back button, it throws an error.

```
Error: Uncaught (in promise): TypeError: e.done is not a function
TypeError: e.done is not a function
    at e._fireError (http://localhost:8101/build/vendor.js:1:280416)
    at e._failed (http://localhost:8101/build/vendor.js:1:280301)
    at http://localhost:8101/build/vendor.js:1:281125
...
```

EDIT: it also happens with the Android device back button.

**Expected behavior:**
Navigating back and forth with browser buttons work without error, same as what we would have by using the app buttons (e.g. header bar back button).

**Steps to reproduce:**
- [Online demo](https://antoine-ion-nav-test.firebaseapp.com/): open dev tool, click the button to navigate and click browser back button. See the error in the console. In dev mode, it is also freezing the screen since errors are strongly reported.
- [Demo app sources on github](https://github.com/antoineol/ion-nav-test), you can check the code, run locally and check the commit for steps.
- Approximate steps (details in the source commit):
  - Generate a project with Ionic CLI with blank template
  - Generate a new page (`ionic generate page page1`)
  - Edit the home page to use `@IonicPage` annotation, add the corresponding module and remove references from `AppModule`
  - Add a simple navigation directive somewhere in the home page: `<button ion-button navPush="Page1Page">Go to page 1</button>`
- I couldn't make a working plunker with the new deeplink config (annotation and no direct references). _[My attempt](http://plnkr.co/edit/MpoB595OozeXqCl6DXNF?p=preview)_

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-ionic-angular : 1.4.0 (C:\nw\proto\ion-test-simple-nav\node_modules\@ionic\cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (C:\nw\proto\ion-test-simple-nav\node_modules\@ionic\cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (C:\nw\proto\ion-test-simple-nav\node_modules\ionic)

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.2.1
    OS   : Windows 10
    npm  : 5.3.0 
```

**Comment by olegwn** [comment]
Same stuff here :( Browser back button breaks the app with errors

**Comment by antoineol** [comment]
In my small app, I couldn't find what could be broken in the production build, except a very unpleasant error logged. The navigation still worked. Although I wouldn't trust it in bigger apps.

But in development with Ionic CLI, yes, it is breaking the app (like any error).

**Comment by jgw96** [comment]
Hello all! Thanks for using Ionic. We will look into this.

**Comment by vhb56** [comment]
Getting similar error, shows error window, doesn't break my app after closing error window!

`Error: Uncaught (in promise): TypeError: ti.done is not a function
TypeError: ti.done is not a function
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:44066:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:44057:14)
    at http://localhost:8100/build/vendor.js:44112:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4770:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9223)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)
    at http://localhost:8100/build/polyfills.js:3:14076
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4761:37)
    at c (http://localhost:8100/build/polyfills.js:3:13535)
    at http://localhost:8100/build/polyfills.js:3:14107
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4761:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
    at o (http://localhost:8100/build/polyfills.js:3:2203)
    at <anonymous>`

**Comment by pjhartin** [comment]
Same error here guys:

Runtime Error
``` 
Uncaught (in promise): TypeError: ti.done is not a function TypeError: ti.done is not a function at
NavControllerBase._fireError (http://localhost:8100/build/vendor.js:47902:16) at
NavControllerBase._failed (http://localhost:8100/build/vendor.js:47893:14) at
http://localhost:8100/build/vendor.js:47948:59 at t.invoke (http://localhost:8100/build/polyfills.js:3:9283) at
Object.onInvoke (http://localhost:8100/build/vendor.js:4657:37) at t.invoke
(http://localhost:8100/build/polyfills.js:3:9223) at r.run (http://localhost:8100/build/polyfills.js:3:4452) at
http://localhost:8100/build/polyfills.js:3:14076 at t.invokeTask
(http://localhost:8100/build/polyfills.js:3:9967) at Object.onInvokeTask
(http://localhost:8100/build/vendor.js:4648:37) 
```

Stack
```Error: Uncaught (in promise): TypeError: ti.done is not a function
TypeError: ti.done is not a function
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:47902:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:47893:14)
    at http://localhost:8100/build/vendor.js:47948:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4657:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9223)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)
    at http://localhost:8100/build/polyfills.js:3:14076
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4648:37)
    at c (http://localhost:8100/build/polyfills.js:3:13535)
    at http://localhost:8100/build/polyfills.js:3:14107
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4648:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
    at o (http://localhost:8100/build/polyfills.js:3:2203)
    at <anonymous>
```

Environment
```
Ionic Framework: ^3.6.0
Ionic App Scripts: 2.1.3
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.11.0
OS Platform: Linux 4.10
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
```

**Comment by Alberick** [comment]
I'm also having this error guys.

**Comment by antoineol** [comment]
Guys, please click 👍 on the original post to add weight to this issue instead of answering +1 :)

**Comment by pavel-kurnosov** [comment]
Same issue, looks like it is not happening if you have page1 -> page2, but if you have page1 -> page2 -> page3 then it is happening on page1 when you press back button to return to previous screen.

**Comment by wf9a5m75** [comment]
![multiple_maps](https://user-images.githubusercontent.com/167831/28945345-f081845c-785a-11e7-96bb-dcd9f615111c.gif)

**Comment by yemenifree** [comment]
I also have the same issue but when pop up to page not in history stack ( default behavior is creating instance of the page and set it as root for nav)

```js
this.navCtrl.popTo('Page');
```

```
    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.2 browser 4.1.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node       : v8.2.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.1.0 
    npm        : 5.3.0 

```

**Comment by janpio** [comment]
Another one here: https://forum.ionicframework.com/t/history-back-error/100967 The topic also contains a Github repo of the bug in action. Clone, npm install, ionic serve and use browser back button to trigger.

**Comment by azurvii** [comment]
With the same project source code, down grade packages `ionic-angular` to `3.5.3`, and `ionic` to `3.6.0` seems to get browser back button working again (modify the `package.json` at the project root, and run `npm install` at the project root). Tested on a simple project and it worked for me, which may serve as a *workaround* till it's fixed if you don't mind regression and if it does not break other things.

**Comment by azurvii** [comment]
However the browser forward/backward buttons seem to clear all NavController stack (worth a different bug i think), which does not act in the same way as using the ionic navigation gadgets.

**Comment by clemishow** [comment]
Same issue 

```
cli packages: (/Users/dev/DEV/MOBILE/myapp/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.3
    Node              : v6.11.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
    ios-deploy        : 1.9.0
    ios-sim           : 5.0.8
    npm               : 5.3.0
```

**Comment by soumak77** [comment]
Root cause of issue was attempting to call done callback before checking if it exists.  The PR which resolve this issue also provides better type support for the function callback so that type checking can detect potential issues.

**Comment by soumak77** [comment]
Is anyone from Ionic going to resolve this issue?  It was introduced 3 weeks ago due to poor code testing and a PR was proposed over a week ago and still no one has responded.

Is anyone from the community aware of an easy way to maintain your own Ionic repo?  The design of the repo makes it impossible to simply link to a different github fork within the npm package.json.  I'm having to compile my changes and copy them locally before each build, but this process breaks when trying to run my automated build/deploy scripts.

**Comment by ChezRD** [comment]
@soumak77 actually you can make fork
1. Fork ionic
2. Run compile part from package.json and mv dist directory outside, into bare git repository that mirrored somewhere
3. Push changes into that repo

You can check my fork to see how you can make it

**Comment by soumak77** [comment]
@ChezRD creating a bare git repo with just the dist folder is a good idea.  Are you able to use the git url in your package.json when doing this?

**Comment by ChezRD** [comment]
Yes. You can add my ionic-angular repo as npm package to test

22 авг. 2017 г. 2:34 пользователь "Brian Soumakian" <
notifications@github.com> написал:

**Comment by karansharma27** [comment]
Is there any solution to this problem, cz I too am facing this issue and I need to publish my app on production. I cannot go live with this issue..

**Comment by olegwn** [comment]
any word from Ionic team about this issue? 1 month has passed since this bug was introduced and still no fix though pull request was submitted by @soumak77 . Very disappointing ;(

**Comment by sommerper** [comment]
Had this problem as well. Currently downgraded Ionic but it would be nice to run the latest version again.

**Comment by jerrydeng** [comment]
@sommerper which downgraded version works?

**Comment by JaminFan** [comment]
Same problem.

**Comment by sommerper** [comment]
@jerrydeng can't remember exactly what i changed but my package.json looks like this:

```
{
  "name": "xxxx",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/deeplinks": "^4.1.0",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic/storage": "2.0.1",
    "cordova-plugin-console": "^1.0.5",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.1",
    "ionic-angular": "3.5.3",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "2.1.3",
    "@ionic/cli-plugin-cordova": "1.6.2",
    "@ionic/cli-plugin-ionic-angular": "1.4.1",
    "ionic": "3.6.0",
    "typescript": "2.3.4"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {}
    },
    "platforms": []
  }
}
```

**Comment by nitinpund** [comment]
Is there any solution available? we are  not able to use  latest ionic update

**Comment by jerrydeng** [comment]
@sommerper thank you

**Comment by vhb56** [comment]
Also got this, everything is up to date.

**Comment by kensodemann** [comment]
@vhb56 - the PR that fixes this has been merged, but we are not ready to do a release yet. We are trying to get a few more fixes in.

**Comment by brassier** [comment]
@kensodemann - Any idea on timeline for this release?  I'm trying to determine if I should roll back to 3.5.3 or wait for the fix.

**Comment by kensodemann** [comment]
Preparing to create a release that will fix this, we created an `ionic-angular@nightly` with @soumak77's PR merged into it. While I believe his changes were necessary (especially the guard around not calling `done()` from tabs if it does not exist, it did not actually fix this issue so I am re-opening it.

**Comment by kensodemann** [comment]
@danbucholtz found and fixed the underlying issue. We now have a nightly build that includes the fix for this issue. I have tested that build using the original repo supplied by @antoineol and it solves this issue.

If you would like to test in your own project(s) you can do an `npm install ionic-angular@nightly` to get this build. This is being done in preparation for a new release so any testing you could do would be very helpful.

**Comment by signuspl** [comment]
I'v had the same problem in my simple project - after nightly build everything works perfect :) thank you very much!

**Comment by brassier** [comment]
Looks like this was fixed in 3.6.1 for me too.  Thanks!

**Comment by FanFanFantastic** [comment]
PLZ help guys, I tried "npm update -g cordova ionic" and when I do ionic -v it says I have 3.18.0 but in the browser I still have the same issue. 
Chrome browser console: Ionic .... it says I have version 3.6.0 

How do I correctly update???

**Comment by ChezRD** [comment]
@FanFanFantastic remove node_modules
