### ISSUE TITLE
ios statusbar layout not right when using mode: md

### ISSUE THREAD

**Issue by media4learning** [ionic-team/ionic#13171]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

I have updated to all latest ionic-angular, plugins etc in the ios 11 checklist. In my app module I have:

```
IonicModule.forRoot(MyApp,{
      preloadModules: true,
      // backButtonIcon: 'md-menu',
      platforms: {
        ios: {
          mode: 'md',
        },
        windows: {
          mode: 'md',
        }
      }
    }
```

The fixes for the ios11 safe-area-inset-top don't seem to have taken this fully into account.

**Expected behavior:**

Shouldn't have to manually override css for ion-navbar etc

**Steps to reproduce:**

I guess all you would need to do it add this to your IonicModule config: 

```
IonicModule.forRoot(MyApp,{
      preloadModules: true,
      // backButtonIcon: 'md-menu',
      platforms: {
        ios: {
          mode: 'md',
        },
        windows: {
          mode: 'md',
        }
      }
    }
```

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
cli packages: (/Users/chrisdelambert/Documents/wfcpg/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v8.1.4
    npm               : 5.1.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : pro

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! We will look into this.

Thank you for using Ionic

**Comment by mhartington** [comment]
Hmm, Im not seeing in my test. I deployed and app to iPhoneX Sim using nightly and it seems to be adjusting things correctly. 

I will note that your ionic info shows you have `Ionic Framework    : ionic-angular 3.7.0` which does not have the ios11 fixes 

![screen shot 2017-10-18 at 10 07 55 am](https://user-images.githubusercontent.com/2835826/31723266-5f7a1de8-b3ec-11e7-8908-b4e36b8084bd.png)

**Comment by media4learning** [comment]
Thanks for looking into this. So what version of ionic-angular should I be using? 

What I am seeing is the padding-top property is being stripped out - so on 10.3.3 padding-top is calc(safe-area.....). The calc(20px + 4px) isn't there. Could this be a SASS issue where it is stripping out the duplicate padding-top property? See screenshot - side by side ios 10.3.3 and ios 11. Neither are correct.

![screenshot 2017-10-20 12 28 10](https://user-images.githubusercontent.com/20275947/31798783-49214cea-b592-11e7-91c7-0f77520903e7.png)

**Comment by media4learning** [comment]
ionic-angular@nightly installed just now does help but it's still not right...
![screenshot 2017-10-20 12 35 20](https://user-images.githubusercontent.com/20275947/31798902-37a7aeea-b593-11e7-99a6-1ceb40c257cf.png)

cli packages: (/Users/chrisdelambert/Documents/stjohncpg/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1-201710181432

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v8.1.4
    npm               : 5.1.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : pro

**Comment by media4learning** [comment]
See how the other padding-top properties are missing. I'm not sure but is this just a SASS issues where duplicates are being ignored? 
![screenshot 2017-10-20 12 41 45](https://user-images.githubusercontent.com/20275947/31799021-0fce3d02-b594-11e7-9cc1-b2b5a770667b.png)

![screenshot 2017-10-20 12 39 06](https://user-images.githubusercontent.com/20275947/31798982-bfbb4602-b593-11e7-835b-d024bddaa96f.png)

**Comment by media4learning** [comment]
I can confirm for some unknown reason the other padding-top properties are being stripped out of the css - this screenshot is from the build folder in platforms/ios/build/www/build/main.css... (formatted for readability)

If I manually copy over the styles it works great. Even on iphone X!
 
![screenshot 2017-10-20 12 58 23](https://user-images.githubusercontent.com/20275947/31799403-69b616e4-b596-11e7-8dc4-174035511c2f.png)

**Comment by mhartington** [comment]
Are you deploy prod builds? If so, what version of  app-scripts are you using?

**Comment by media4learning** [comment]
Yes I am running ionic cordova build ios --prod

@ionic/app-scripts : 3.0.0

**Comment by mhartington** [comment]
Can you try `npm i @ionic/app-scripts@nightly`. This should be fixed in nightly (dependency update)

**Comment by media4learning** [comment]
That did the trick - it also pulled though some extra css that was missing for iphone X etc. Thanks so much for your quick replies, really appreciate your help - and your work in general :)

**Comment by mhartington** [comment]
🎉  Perfect, I'll get a proper release out tomorrow morning (8:30pm for myself)
