### ISSUE TITLE
Module Parse Runtime Error after upgrading from 3.7.1 to 3.9.2

### ISSUE THREAD

**Issue by imagine4me** [ionic-team/ionic#13379]
**Ionic version:**
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
After diligently following all the upgrade instructions for going from 3.7.1 to 3.9.2, I'm no longer able to run the app because of the following error:

```
Uncaught Error: Module parse failed: Unexpected token (144:4294)
You may need an appropriate loader to handle this file type.
|     ListingsPage = __decorate([
|         Component({
|             selector: 'page-listings',template:/*ion-inline-start:"/Users/user1/Documents/DEV/app1/src/pages/listings/listings.html"*/`<ion-header...'
 }),
|         __metadata("design:paramtypes", [typeof (_b = typeof App !== "undefined" && App) === "function" && _b || Object, typeof (_c = typeof ModalController !== "undefined" && ModalController) === "function" && _c || Object, typeof (_d = typeof NavController !== "undefined" && NavController) === "function" && _d || Object, typeof (_e = typeof Events !== "undefined" && Events) === "function" && _e || Object, typeof (_f = typeof DataService !== "undefined" && DataService) === "function" && _f || Object, typeof (_g = typeof AuthService !== "undefined" && AuthService) === "function" && _g || Object])
    at Object.341 (main.js:4935)
    at __webpack_require__ (bootstrap 2bf6fbfbcb9dcc85640a:54)
    at Object.336 (rental-details.module.ts:17)
    at __webpack_require__ (bootstrap 2bf6fbfbcb9dcc85640a:54)
    at Object.431 (main.js:6105)
    at __webpack_require__ (bootstrap 2bf6fbfbcb9dcc85640a:54)
    at Object.368 (main.ts:5)
    at __webpack_require__ (bootstrap 2bf6fbfbcb9dcc85640a:54)
    at Object.345 (keyboard-attach.module.ts:16)
    at __webpack_require__ (bootstrap 2bf6fbfbcb9dcc85640a:54)
```

**Expected behavior:**
App should still work after the upgrade. 

It feels like there's something obvious that my cold-afflicted brain is overlooking, but I cannot quite put my finger on it yet.

**Steps to reproduce:**
I've spun up a new Ionic tabs application with some additional pages and components, and I'm yet unable to reproduce this error.

**Other information:**

The following resolved issue from a year ago is the closest to the error I'm seeing, but its resolution doesn't really work/make sense (as the newly spun up Ionic app has no issues with components outside the 'app' folder): [https://github.com/ionic-team/ionic/issues/5482](https://github.com/ionic-team/ionic/issues/5482)

**Ionic info:**

```
cli packages: (/Users/user1/Documents/DEV/app1/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.1
    ios-sim    : 5.0.8
    Node       : v6.9.3
    npm        : 3.10.10
    OS         : macOS Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by nateOVO** [comment]
Same issue here.

>Runtime Error
>Uncaught (in promise): Error: Module parse failed: Unexpected token (830:4499) You may need an appropriate loader to handle this file type.

In my case, downgrading `@ionic/app-scripts` from 3.1.0 back to 3.0.1 seemed to fix it.

===

Ionic Info:
```
cli packages: (/Users/<user>/.npm-packages/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : ios 4.5.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.1.4
    npm        : 5.0.3 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by ptsimpso** [comment]
I have this same issue, but running npm install --save @ionic/app-scripts@3.0.1 did not resolve. This just resulted in more errors:
```
Error: Cannot find module '@angular/tsc-wrapped/src/tsc'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ptsimpso/Desktop/Freelancing/Shortcut/repos/vibes-app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:6:13)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

**Comment by gbrigens** [comment]
I am getting the same error too https://stackoverflow.com/questions/47219099/module-parse-failed-unexpected-token-ionic-3

**Comment by pyboosted** [comment]
I believe the problem appeared in [this commit](https://github.com/ionic-team/ionic-app-scripts/commit/484d90d). 

Replacing \` to ' in `node_modules/@ionic/app-scripts/dist/template.js:153` helps:
```javascript
return getTemplatePrefix(htmlFilePath) + "'" + content + "'" + getTemplateSuffix(htmlFilePath);
```

**Comment by gbrigens** [comment]
@pyboosted thanks so much you save me, this was a headache to me 👍 .

**Comment by bitdistrict** [comment]
Same problem here... downgrading to app-scripts 3.0.1 fixes the issue. But with angular 5 aot build doesnt work without the newest version of app-scripts... So the hack is the only one solution for both things now.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by lincolnthree** [comment]
I am also having this issue in my large (non-sample) Ionic app.

**Comment by lincolnthree** [comment]
The fix from @pyboosted seems to resolve my issue (and I'm on to another one now.)

**Comment by imagine4me** [comment]
This issue has been resolved with app-scripts release 3.1.1+ (https://github.com/ionic-team/ionic-app-scripts/releases/tag/v3.1.1) - thanks to @pyboosted for the quick find!

**Comment by smrgrg** [comment]
I am using ionic app-scripts 3.1.11 but still faced the same issue. The fix from @pyboosted seems to solve my issue as well. Thanks @pyboosted for solving my headache.

**Comment by smrgrg** [comment]
Actually, I figured out the issue. Webstorm did not display encoded texts, which came along when I copied a bunch of texts from some outside source. However, when I opened the same file in Visual Studio Code, it showed me the encoded text. After I deleted those texts, the issue was gone.
