### ISSUE TITLE
Ion-tabs breaks when using ion-refresher

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic#14430]
**Ionic version:**
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**
[X] bug report
[ ] feature request

**Current behavior:**
If you add `ion-refresher` to one of my tabs pages, the tabs are not longer responsive. Tap/click and nothing happens. No errors in console.

**Expected behavior:**
`ion-refresher` should work without breaking other components

**Steps to reproduce:**
1. create new tabs project
2. add `ion-refresher` to one of the tabs pages
3. observe clicking on a tab does not change the page

**Related code:**
Codepen https://codepen.io/corysmc/pen/LmjMOK?editors=1010
Comment out the `ion-refresher` and it works. ^^

**Other information:**
Note that when running an app with lazy loading, the tabs will work until the page with the `ion-refresher` is loaded. For the codepen example, it's all loaded at once, so the bug is there on load.

**Ionic info:**
```
@ionic/core@4.0.0-alpha.4
```

**Comment by mhartington** [comment]
This should be fixed in the next release. Basically refresher was attaching it's gesture listeners to `window`, and would block events if you were mid pull, or if it scrolling a bit. Gesture was moved to attach to the parent ion-content instead.

**Comment by corysmc** [comment]
So this fixed tabs! 🎉 
However, Still having issues with interactions on the same page:
Updated the codepen: https://codepen.io/corysmc/pen/LmjMOK?editors=1010

**Comment by mhartington** [comment]
Right you are. Cool looks like some other quirk is going on. Looking into it.

**Comment by brandyscarney** [comment]
I discussed this issue with Cory in Slack and he is getting the following error now:

```
ion-refresher didn't attached, make sure if parent is a ion-content
```

So I am going to close this issue in favor of #14833 since that is the current error now. Please let me know if I'm wrong on this Cory! Thanks!
