### ISSUE TITLE
[Ionic v4 with angular| Slides ionSlideWillChange and ionSlideDidChange outputs not working

### ISSUE THREAD

**Issue by bilalrazamoon** [ionic-team/ionic#14917]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/Users/bilal/.config/yarn/global/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v8.9.4 (/Users/bilal/.nvm/versions/node/v8.9.4/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/bilal/Library/Android/sdk
```

**Describe the Bug**
Slides `ionSlideWillChange` and `ionSlideDidChange` outputs not call when slide changed.

**Steps to Reproduce**
1. Go to stackblitz example.
2. Change slide.
3. Check console.

**Related Code**
https://stackblitz.com/edit/ion-slides-outputs

**Expected Behavior**
It should call `ionSlideWillChange` and `ionSlideDidChange` outputs when slide changes.

**Comment by netsesame2** [comment]
I've the same issue.

**Comment by netsesame2** [comment]
It's resolved in "@ionic/core": "^4.0.0-beta.1"

**Comment by frenmanoj** [comment]
The fix under @4.0.0-beta.1 works only for the effect type **slide**. It still doesn't work for the effect type **coverflow**.
