### ISSUE TITLE
[ionic v4 - angular] - iPhone X don't show header and tabs correctly (missing safe area)

### ISSUE THREAD

**Issue by SoulOnFire** [ionic-team/ionic#14940]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/Users/u007240/.npm-packages/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

System:

   NodeJS : v10.7.0 (/usr/local/Cellar/node/10.7.0/bin/node)
   npm    : 6.2.0
   OS     : macOS High Sierra
```

**Describe the Bug**
Every starter came without padding for the safe area in iPhone X for the Notch.

**Steps to Reproduce**
1. ionic start myApp [tabs|menu|blank] --type=angular
![captura de ecra 2018-07-30 as 16 16 26](https://user-images.githubusercontent.com/642845/43406374-fce96482-9413-11e8-8aef-4647f18ca64a.png)

**Comment by mswilson4040** [comment]
Also seeing this as well....

**Comment by carstenbaumhoegger** [comment]
I'm also having the exact same problem!

**Comment by mswilson4040** [comment]
This may not be an ionic 4 issue, but an iPhoneX issue instead. I say this because after some looking around at who actually uses ionic, I ran accross this site: http://showcase.ionicframework.com/apps/top

I downloaded a couple of their apps, notably, Markey Watch and I can see this exact same issue there. Given Ionic 4 is in beta and was just released a couple days ago, my assumption is that Market Watch isn't using ionic 4 which would mean this issue is found in multiple Ionic versions.

**Comment by SoulOnFire** [comment]
@mswilson4040 this could be in fact something not related with ionic but in fact if we do any of the start templates in ionic 3 removing  "--type=angular " ```ionic start myApp [tabs|menu|blank]``` all works as expected. Some of the apps in the market are incompatible with iPhone X because are created before ionic have iOS 11 support. 

In order to resolve this issue I add the following css to the global.scss
```css
body {
    background-color: var(--ion-color-primary);
}
ion-app {
    margin-top: env(safe-area-inset-top);
    margin-bottom: env(safe-area-inset-bottom)
}
```

**Comment by gabrielmaldi** [comment]
Related to #14742

**Comment by mswilson4040** [comment]
@SoulOnFire Can you expand on where the `env` function is imported from?

**Comment by gabrielmaldi** [comment]
This is now fixed in `beta.3`.

**Comment by babaru** [comment]
Please let me clarify this a bit:

The bottom Tab bar works just fine while the header height seems still not corrent. Please find a screenshot as follow:

![wechatimg224](https://user-images.githubusercontent.com/60080/46187182-f27f6e80-c314-11e8-9ad0-150e027001f5.jpeg)

Sorry it may not be able to see the notch from this screenshot but it's still clear the header area is a bit lower than it should be.

Thanks!

**Comment by mhartington** [comment]
@babaru Please make sure you're updating the starter to use beta.12 of `@ionic/angular`. By default they're using beta-7 right now (we need to update the base project).

With beta 12, things look as expected

![screen shot 2018-09-28 at 10 56 34 am](https://user-images.githubusercontent.com/2835826/46216349-5dc54280-c30d-11e8-9118-f74e596814b3.png)
