### ISSUE TITLE
[ionic 4] nav component

### ISSUE THREAD

**Issue by zhaoaiyuan** [ionic-team/ionic#15254]
# Support Question

Using nav component to report errors:

 Error: StaticInjectorError(AppModule)[MySetPage -> Nav]: 
  StaticInjectorError(Platform: core)[MySetPage -> Nav]: 
    NullInjectorError: No provider for Nav!

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Comment by bkarv** [comment]
Have same issue when trying to import nav into my component constructor

**Comment by paulstelzer** [comment]
This is issue should be resolved in beta.17. If I am wrong, please write here!

**Comment by dankawka** [comment]
@paulstelzer 
```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.11.0
   @angular-devkit/schematics    : 7.1.0
   @angular/cli                  : 7.1.0
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/daniel/Android/Sdk)
   NodeJS            : v8.14.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.18
```

Got `public nav: Nav` in constructor but error is still present:
```
ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[HomePage -> Nav]: 
  StaticInjectorError(Platform: core)[HomePage -> Nav]: 
    NullInjectorError: No provider for Nav!
```

**Comment by paulstelzer** [comment]
And @dankawka please make sure to add `IonicModule.forRoot()` into your app.module.ts
