### ISSUE TITLE
Ionic 4.beta3 slidebox lockSwipes() is not working

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic#15310]
On doing swipe lock I am getting an error.

```
updateSlideBox() {
            var slideController = document.querySelector(".slidernow");
            slideController.componentOnReady().then(function () {
              slideController.update();
              slideController. lockSwipes();
            });
        }
```

```
jepizrms.js:5 Uncaught (in promise) TypeError: this.swiper.unlockSwipeToNext is not a function
    at k.lockSwipeToNext (jepizrms.js:5)
    at eval (Airport.js?3dca:146)
```

I can tell slideTo is working fine but locking swipes of slides is throwing error.

Ionic version:
<script src="https://unpkg.com/@ionic/core@4.0.0-beta.3/dist/ionic.js"></script>

**Comment by olivier-po** [comment]
I confirm. I have the same issue with lockSwipes (using beta 7)

```Uncaught (in promise): TypeError: this.swiper.unlockSwipes is not a function
TypeError: this.swiper.unlockSwipes is not a function```

**Comment by fabrv** [comment]
LockSwipes() isn't working but I found a workaround.

You have to disable swiping from the 'Sliders' options. There are a couple of ways of doing it (check [Swiper Docs](http://idangero.us/swiper/api/)) but this is how I did it:

HTML:
`<ion-slides [options]="slideOpts"></ion-slides>`

TS:
```
slideOpts: any = {allowTouchMove: false};

LockSwipes( lock: boolean ){
  if (lock == true){
    this.slideOpts =  {allowTouchMove: true};
  }else{
    this.slideOpts =  {allowTouchMove: false};
  }
}
```

With this code simply call the function LockSwipes and you are ready to go. :)

**Comment by paulstelzer** [comment]
This is issue should be resolved in beta.17. If I am wrong, please write here!

**Comment by synga** [comment]
Still not working in beta.17, using the `allowTouchMove: false` in the options instead.

My code:

```
ngAfterContentInit() {
  this.slides = document.querySelector('ion-slides');
  this.slides.lockSwipes();
}
```
