### ISSUE TITLE
[ionic 4 beta 3] menuController enable method not working on first page loaded

### ISSUE THREAD

**Issue by VincentPuget** [ionic-team/ionic#15343]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/Users/user/.nvm/versions/node/v8.11.2/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/user/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v8.11.2 (/Users/user/.nvm/versions/node/v8.11.2/bin/node)
   npm               : 6.4.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
When i reload my application on /login page, side menu is not disabled.

I want to disable sidemenu on some pages, /login for example.

It's working properly when i load /home page first then i navigate to /login page. Sidemenu desapear as expected.

**Related Code**
```typescript
import { Component, OnInit } from '@angular/core';
import { MenuController } from '@ionic/angular';

@Component({
  selector: 'app-login',
  templateUrl: './login.page.html',
  styleUrls: ['./login.page.scss'],
})
export class LoginPage implements OnInit {

  constructor(
    private menuController: MenuController
  ) {}

  ngOnInit() {}

  ionViewWillEnter() {
    this.menuController.enable(false);
  }

  ionViewDidLeave() {
    this.menuController.enable(true);
  }

}

```
If a use a setTimeout of 100 or 200 ms to call enable method, side menu desapears but it's not very clean...

``` typescript
ionViewWillEnter() {
    const timer = setTimeout(() => {
        clearTimeout(timer);
        this.menuController.enable(false);
    }, 100);
}
```

Another work-around is to show ion-menu when window.location.pathNameis not equal to /login with a *ngIf directive. It's working but i find this not very clean too...

**Expected Behavior**
I want to disable sidemenu on some pages, /login for example.

**Additional Context**
Issue posted on stackoverflow 
https://stackoverflow.com/questions/51988283/ionic-v4-menucontroller-enable-method-not-working-on-first-page-loaded

**Comment by VincentPuget** [comment]
This is not resolved with Ionic 4.0.0-beta.5

**Comment by dacrypt** [comment]
I also have this problem. It fails to hide the menu randomly.

**Comment by ronwondaal** [comment]
Same problem here, MenuController.enable(false) will not disable the menu on page init/load/view

**Comment by 777wills** [comment]
neither is it resolved in beta

**Comment by jaipresto** [comment]
I had a similar problem with the _MenuController_ and banged my head against a wall for longer than I'll disclose before realising it'd wise to read the ionic core docs.

I had multiple side menus, set to _false_ by default, which had to be enabled on particular pages. But MenuController wasn't recognising the _id's_ I was passing in.

Concussed to the point of unconsciousness, I opened the ionic core docs on github and learned that MenuController now looks for menu-id, not id. So:

    <ion-menu menu-id="justAnotherMenu">...

grabbed by, for instance:

    this.menuCtrl.enable(true, 'justAnotherMenu')

works.

As always, it seems so obvious.

**Comment by jaipresto** [comment]
> I had a similar problem with the _MenuController_ and banged my head against a wall for longer than I'll disclose before realising it'd wise to read the ionic core docs.
> 
> I had multiple side menus each with a unique _id_, set to _false_ by default, which had to be enabled on particular pages. But MenuController wasn't recognising the id's I was passing in.
> 
> Concussed to the point of unconsciousness, I opened the ionic core docs on github and learned that MenuController now looks for _menu-id_, not id. So:
> 
> ```
> <ion-menu menu-id="justAnotherMenu">...
> ```
> grabbed by, for instance:
> 
> ```
> this.menuCtrl.enable(true, 'justAnotherMenu')
> ```
> works.
> 
> As always in retrospect, both the new method and the solution to finding it seem so obvious.

I should note however that the MenuController still isn't working as it should be, even though it now recognises the id. If I place the enable code inside the constructor or ngOnInit, it doesn't do anything. It's like the controller takes too long to load. Hence I'm currently enabling the menu(s) with @HostListener, which isn't optimal.

**Comment by Celtiore** [comment]
hi,
read my comment here : https://github.com/ionic-team/ionic/issues/15916

check my repo, I do some tests : 

https://github.com/Celtiore/ionicV4-multiples-sidemenus

**Comment by paulstelzer** [comment]
That seems related to my issue #16376 , but I couldn't reproduce it

So it's still an issue in beta.17, correct?

**Comment by javieraviles** [comment]
Seems to be working fine for me after updating to 4.0.0-beta.17 (was not working before with beta.12), can somebody else give it a try?

**Comment by manucorporat** [comment]
This should be fixed in latest version of Ionic 4!
