### ISSUE TITLE
[ionic4beta13] AlertController/Alert Usage and NgZone

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic#16014]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\rtpha\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.13
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
If you look in this thread you will see the discussion. It's not clear to me if this is a bug / something unfinished with the AlertController or if its something that's not covered by the docs:

https://forum.ionicframework.com/t/alertcontroller-ionic-4-beta-7-navigation-triggered-outside-angular-zone-did-you-forget-to-call-ngzone-run/142332/10

To summarise, the handlers for buttons in an `Alert` has some confusing usage issues. 

In one scenario attempting to use `this.navController.navigateForward("/");` will actually redirect to the destination but an error appears in the log:

    Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?

In another scenario I had a delete function called from the confirm button handler of an `Alert` and on the ok it would delete that item from the data but the ui wasn’t being refreshed. This meant that it was still in the list of cards in the UI but no longer in the data. 

In both cases using the NgZone solution mentioned in the forum post got things working.

I did some research and actually didn’t expect this to work as the Angular docs say zone is for when you update the data that you _don’t_ want Angular to monitor and update, but I wanted the opposite. It worked anyway.

I'm not clear on what NgZone is really for so thats why I'm not sure if this is a bug in my code, in the Alert or just that the docs are missing saying this is needed?

**Related Code**
First example I described (the solved code that got it working):

```
  async buttonCancel() {
    const alert = await this.alertController.create({
      header: 'Reset',
      message: 'Do you want to reset back to the homepage?',
      buttons: [
        { 
          text: 'No',
          role: 'cancel',
          cssClass: 'secondary'
        }, {
          text: 'Yes',
          handler: () => {
            // https://forum.ionicframework.com/t/alertcontroller-ionic-4-beta-7-navigation-triggered-outside-angular-zone-did-you-forget-to-call-ngzone-run/142332/8
            this.zone.run(async () => {
              this.beerbargainService.resetOffers();
              this.navController.navigateForward("/");
            });
          }
        }
      ]
    });

    await alert.present();
  }
```

Second example I described (again the solved issue):

```
  async buttonRemoveOffer(i) {
    const alert = await this.alertController.create({
      header: 'Delete Offer',
      message: 'Are you sure you want to delete this offer?',
      buttons: [
        { 
          text: 'No',
          role: 'cancel',
          cssClass: 'secondary'
        }, {
          text: 'Yes',
          handler: () => {
            this.zone.run(async () => {
              this.deleteOfferByIndex(i);
              this.saveOfferToBeerOffers();
            });
          }
        }
      ]
    });

    await alert.present();
  }
```

The unsolved versions of both of these is just the removal of the `this.zone.run(async () => {` line and its closing `});`.

**Expected Behavior**
I'm looking for guidance here.

**Additional Context**
Original snippets were both adapted from the docs at https://beta.ionicframework.com/docs/api/alert/

**Comment by mhartington** [comment]
👋 Hi there. This was an issue last release that I though was fixed by @manucorporat via https://github.com/ionic-team/ionic/commit/f63c0f5ccc8dad9958861b13e465432ddd8cd89b

Can you confirm that you have beta 13 installed?

**Comment by rtpHarry** [comment]
I have beta 13 installed.

This is from my `packages.json`:

```
"dependencies": {
    "@angular/common": "~6.1.1",
    "@angular/core": "~6.1.1",
    "@angular/forms": "~6.1.1",
    "@angular/http": "~6.1.1",
    "@angular/platform-browser": "~6.1.1",
    "@angular/platform-browser-dynamic": "~6.1.1",
    "@angular/router": "~6.1.1",
    "@ionic-native/core": "5.0.0-beta.15",
    "@ionic-native/splash-screen": "5.0.0-beta.15",
    "@ionic-native/status-bar": "5.0.0-beta.15",
    "@ionic/angular": "^4.0.0-beta.13",
    "core-js": "^2.5.3",
    "rxjs": "6.2.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "~6.1.1",
    "@angular/compiler": "~6.1.1",
    "@angular/compiler-cli": "~6.1.1",
    "@angular/language-service": "~6.1.1",
    "@angular-devkit/architect": "~0.7.2",
    "@angular-devkit/build-angular": "~0.7.2",
    "@angular-devkit/core": "~0.7.2",
    "@angular-devkit/schematics": "~0.7.2",
    "@ionic/ng-toolkit": "^1.0.0",
    "@ionic/schematics-angular": "^1.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.9.2",
    "codelyzer": "~4.4.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  },
```

**Comment by Eyescream** [comment]
> In another scenario I had a delete function called from the confirm button handler of an `Alert` and on the ok it would delete that item from the data but the ui wasn’t being refreshed. This meant that it was still in the list of cards in the UI but no longer in the data.

Hello, I am still seeing this issue with beta15. 
It seems that the handler: ()  function runs OUTSIDE the angular zone

**Comment by RHinderiks** [comment]
Can confirm these issues still exists, we have them in action sheets and such. Not only navigation is problem but also updating the page itself does not happen. runnning beta 16

**Comment by manucorporat** [comment]
This is already fixed in rc.1!

**Comment by JoeBoxr** [comment]
Hello.

This problem still exists in 4.0.1 but only when navigating tabs back and forth.  For example:

this.navCtrl.navigateForward('/tabs/subtab');  doesn't result in a ngZone warning.

Hitting the <ion-back-button defaultHref="/tabs/maintab"></ion-back-button>
and then calling...

this.navCtrl.navigateForward('/tabs/subtab');  results in a ngZone warning.

core.js:16824 Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?

Regards
