### ISSUE TITLE
Ionic 4: DateTime - Start picker on today's date

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic#16436]
#  Feature Request

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.9.0-beta.3
   @angular-devkit/schematics    : 0.9.0-beta.3
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 9 other plugins)

System:

   ios-deploy : 1.9.1
   NodeJS     : v10.10.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
```

**Describe the Bug**
In DateTime when a 'max' is set, the date picker starts at at max value, which makes it a poor UI experience. It should start at current date/time or property to supply a starting point.

**Steps to Reproduce**
In Ionic 4 set Datetime 'max' to a large number and picker will start their.

**Expected Behavior**
Start at today's date or allow us to supply a starting pointl

**Additional Context**
<img width="476" alt="screen shot 2018-11-23 at 11 24 20 pm" src="https://user-images.githubusercontent.com/10624315/48943452-5b7f0d80-ef77-11e8-8917-1fe60f45ee8a.png">
.

**Comment by bryce13950** [comment]
Have you tried adding an initial value to this as todays date?

**Comment by bkarv** [comment]
I was trying to avoid dirtying the form. I can do a work around by having a viewValue and my dataValue. The viewValue is what the date time uses whilst the dataValue updates if the OK button is pressed which now can be controlled though the custom picker options.

However it’s seems a bit of work for something that logically should be available. If you look at angular material date picker which is a good comparison given it’s maturity and popularity, they have a whole section dedicated to setting the initial view. 

https://material.angular.io/components/datepicker/overview

**Comment by bryce13950** [comment]
Yeah it's definitely not ideal, but I am just trying to find a way that you can get around it for the time being. We will let you know when it is fixed!

**Comment by bkarv** [comment]
Thanks for considering, look forward to the fix

**Comment by bkarv** [comment]
Is there any idea when this will be fixed? 

I’ve tried as a work around setting the today date when date is empty using the ionFocus event but still doesn’t work ie displays on max range. 

Is there any other work around available in the interim?

**Comment by liamdebeasi** [comment]
Hi @bkarv,

I have created a PR that will fix this issue: https://github.com/ionic-team/ionic/pull/17443

Hoping to get it merged in soon.

Thanks for using Ionic!

**Comment by bkarv** [comment]
@liamdebeasi thank you, ultimately if we can have a  property that allows us to pass an start view date like today's date that would be awesome

**Comment by liamdebeasi** [comment]
Hi @bkarv,

You should be able to do that already. If you provide a valid ISO string to the `value` prop, it should start the date picker on that date.

Example:

```
<ion-datetime value="2019-02-14T09:00:00.000Z"></ion-datetime>
```

![image](https://user-images.githubusercontent.com/2721089/52791878-fb5cac80-3037-11e9-942b-226fd276cb60.png)

**Comment by bkarv** [comment]
@liamdebeasi Unfortunately no the issue is the value is initially null, if you set this value it will show as as the value set in the UI input not as null. Maybe I wasn't clear what I meant by start view date, I meant the value to be shown when the date selection window is open. It would be great to be able to pass the value for the dial to open on if not value is set. 

But hey right now I settle for it opening on the current date when the value is null. 

Can you just confirm in datetime mode it shows the current local time as I think there was a bug in Ionic 3 when it wouldn't open on the current time. Many thanks for the help on this..

**Comment by liamdebeasi** [comment]
Hi @bkarv,

Thanks for the clarification. In the next release of Ionic (v4.1.0), the datetime component will default to the current date/time when `value` is null.

I will add "being able to set the starting date" as a feature request.

Thanks for using Ionic!

**Comment by bkarv** [comment]
@liamdebeasi Thanks Liam upgraded and looks like it is defaulting to today's time. However it seems like it defaults to GMT time not the local time. Another person has already raised an issue:

https://github.com/ionic-team/ionic/issues/17587

**Comment by liamdebeasi** [comment]
Hi @bkarv,

This has been fixed via #17706 and will be in the next release of Ionic. I have published a nightly build of Ionic with this fix (`npm install @ionic/core@dev`). Feel free to test it out and provide feedback if you have the time.

Thanks!

**Comment by carlos2712** [comment]
Hi @liamdebeasi  I've been using the nightly build (   "@ionic/core": "^4.1.2-dev.201903111954.bab56e8")  in order to have the current date on ion-datetime but I'm still getting the wrong date/hour: 

Example : 

![Item-0_and_Item-0_and_Item-0](https://user-images.githubusercontent.com/37664806/54251573-0cf18100-451e-11e9-8fc9-8e56f0d82719.png)

My code: 
`<ion-datetime  picker-format="MM/DD/YYYY HH:mm"
                  display-format="HH:mm" placeholder="-Select-" [(ngModel)]="item.StartTime"
                  (ionChange)="updateProviderTime(item)">
                </ion-datetime>`

Scenario: 
`item.StartTime = null`

Do I miss something?

**Comment by liamdebeasi** [comment]
Hi @carlos2712,

If you set `item.StartTime = undefined` does that fix it?

Thanks!

**Comment by carlos2712** [comment]
@liamdebeasi 

Nope, It didn't work. I tried with undefined and also like this : 

`   <ion-datetime class="input-style" picker-format="MM/DD/YYYY HH:mm"
                  display-format="HH:mm" placeholder="-Select-" 
                  (ionChange)="updateProviderTime(item)">
                </ion-datetime>`

Like not having values at all. But it didn't work. Any idea? Thanks!

**Comment by liamdebeasi** [comment]
Interesting. The following datetimes are showing the correct date and formatted properly:

```
<ion-datetime picker-format="MM/DD/YYYY HH:mm" display-format="HH:mm" placeholder="-Select-" [value]="undefined"></ion-datetime>
  
<ion-datetime picker-format="MM/DD/YYYY HH:mm" display-format="HH:mm" placeholder="-Select-"></ion-datetime>  
```

The following datetimes are _not_ formatted properly (working on a fix for this):

```
<ion-datetime picker-format="MM/DD/YYYY HH:mm" display-format="HH:mm" placeholder="-Select-" [value]="null"></ion-datetime>  
```

None of these are working for you, correct?

**Comment by carlos2712** [comment]
Yeah, correct look at my screenshot : 

![Item-0_and_Item-0_and_Item-0_and_Item-0](https://user-images.githubusercontent.com/37664806/54285510-7dc58700-4578-11e9-85b8-1933d8ad0558.png)

**Comment by liamdebeasi** [comment]
Thanks for the additional info. Could you post the contents of your `package.json`?

**Comment by liamdebeasi** [comment]
Ah! Make sure you install the nightly `@ionic/angular too (`npm i @ionic/angular@dev`). Sorry, should have specified earlier.

**Comment by carlos2712** [comment]
Thanks!  after update, even though the value is undefined is showing the current time on the input is not respecting the placeholder : 

![Item-0_and_Item-0_and_Item-0_and_Item-0](https://user-images.githubusercontent.com/37664806/54287813-c2ebb800-457c-11e9-8d60-54482c45af81.png)

**Comment by liamdebeasi** [comment]
Great, glad to hear the time is formatting correctly. I will work on a fix for the placeholder issue.

**Comment by carlos2712** [comment]
Thanks! Will be more than happy to test when you get the PR.

**Comment by liamdebeasi** [comment]
I appreciate all the testing you are doing! I pushed a new nightly build a moment ago that should resolve the placeholder issues. There were some discrepancies between the core Ionic component and Angular's `[(ngModel)]` binding that I had to account for, so hopefully I didn't miss any other scenarios 🙂.

**Comment by carlos2712** [comment]
Okay, I will test that out! Thank you for your help!

**Comment by liamdebeasi** [comment]
Hi there,

This has been fixed with the latest version of Ionic (`v4.1.2`)! To get the latest changes, run `npm i @ionic/core@latest @ionic/angular@latest`.

Thanks!
