### ISSUE TITLE
RC.1 with problems in production mode

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/ionic#17034]
# Bug Report

**Ionic version:**

[x] **4.0.0-rc.1**

**Current behavior:**
rc.1 isn't working in production mode ( `ng build --prod` /  `ionic build --prod`  ). if you run without --prod , everything is working

There are already some issues about (see for there console logs):

`Unhandled Promise rejection: c.data is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: c.data is not a function`  (#17032 /  #17033 )

#17029

Other errors are:

- Menu: must have a "content" element to listen for drag events on.

I will close them so we just have one issue about this topic. It's not only related to `@ViewChild()`, ion button disabled is also not working and slides only shows the first side

I did some resarch and the issue must be related in #16966. If I build with this PR, production isn't working anymore. I can be wrong, so everyone can do tests too :)

**Expected behavior:**
Should work in production build too

**Steps to reproduce:**

Add e.g. @ViewChild and try to access to it. Or add a split pane and a menu.

**Comment by rdlabo** [comment]
> icon was not resolved
We must add assets at angular.json in Ionic 4 RC.1.
https://github.com/ionic-team/starters/blob/master/angular/base/angular.json#L29-L31

**Comment by paulstelzer** [comment]
@rdlabo Yes, this is mentioned in the changelog ( https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#breaking-changes ). But if you run in production mode, icons not working ;)

**Comment by rdlabo** [comment]
@paulstelzer Oh. Icon worked in production build in my environment... Maybe cache worked.

**Comment by paulstelzer** [comment]
did you upload it to your server and tried again (cache cleared)?

**Comment by eduardoRoth** [comment]
@paulstelzer icons work for me, but I have the error for slides:
![image](https://user-images.githubusercontent.com/5419161/50962925-efa62500-1490-11e9-9d40-565122ed9e49.png)

**Comment by paulstelzer** [comment]
@manucorporat is already working on it and will add some more tests so something like that will hopefully not happen again :)

**Comment by DreamPWJ** [comment]
We hope to solve the problem as soon as possible. The product must be delivered and launched in these two days, because this problem cannot be used urgently

**Comment by paulstelzer** [comment]
The problem is already solved. If you need it right now, just fork this repo, install all packages and build it. Then you just need to copy it into your node modules.

**Comment by orlyapps** [comment]
@paulstelzer I have build @ionic/angular and copied the package into my node_modules. The issue is still there. Im doing something wrong?

**Comment by paulstelzer** [comment]
could you explain which issue? The ion-slides issue still exist (see #17085 ). But everything else should work, so only thing you can't do is using the slides

**Comment by orlyapps** [comment]
Yep, the ion-slide issue.
Im reverting back to rc.0 - thanks :)

**Comment by paulstelzer** [comment]
@orlyapps the fix for slides is now integrated in the master branch

**Comment by orlyapps** [comment]
<img src="https://media.giphy.com/media/HjPbLbmep2aJO/giphy.gif">

**Comment by paulstelzer** [comment]
Everyone who wants to try it out, youcan  install the latest dev build by npm install @ionic/angular@dev
