### ISSUE TITLE
Newline not working in textarea (Firefox)

### ISSUE THREAD

**Issue by itsmanojb** [ionic-team/ionic#17155]
Default behaviour of enter button in textarea not working properly in firefox.
 
Can be seen in the documentation as well.
Open the following link in firefox, and try entering a new line in ion-textarea.

[https://beta.ionicframework.com/docs/api/textarea/](url)

Even pasting a content with line-breaks doesn't work.

**Comment by manucorporat** [comment]
Can you test updating to `rc.2`? we implemented several fixes around ion-input and ion-textarea!

**Comment by itsmanojb** [comment]
Updated to `"@ionic/angular": "4.0.0-rc.2"`
Issue still persists in Firefox.

**Comment by manucorporat** [comment]
ok thanks! I will take a look then
