### ISSUE TITLE
[v4 - iOS] ion-tab-bar reappearing when switching input focus

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/ionic#17407]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When using Tabs together with a tab bar, the tab bar properly hides when the keyboard openes for input. When switching to another input element while the keyboard is still open, the tab bar appears on top the the keyboard

**Expected behavior:**
The tab bar should stay hidden as long as the keyboard is open.

**Steps to reproduce:**
1. Use the starter app with the latest WkWebView Plugin (3.x) - add multiple inputs (text) to a page.
2. Build for iOS and run on iOS
3. Select any input --> `keyboardWillShow` and `keyboardDidShow` will be properly triggered, the keyboard appears, and the tab bar disappears.
4. With the keyboard being still open, select another input (field). --> triggers `keyboardWillHide` and `keyboardDidHide` and does not trigger the show and didShow events, thus letting the tab bar reappear on top of the keyboard (and messing around with view height calculations).

![ezgif-2-c6ee428492c9](https://user-images.githubusercontent.com/819238/52377083-1772b380-2a64-11e9-9ae0-c35d717f13ce.gif)

**Other information:**
As v3 and v4-beta did not automatically hide the tabs, we worked around this issue by hiding the bar manually (by listening to the Keyboard plugin events first). With v4-stable this seems to be done by the tabs itself - but it also seems to be partially broken

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   Android SDK Tools : 25.2.2 (/Users/xxx/Library/Android/sdk)
   NodeJS            : v8.12.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by wilk-polarny** [comment]
Update: This issue is still present in 4.3.0 and is a blocker for our app release after migrating to v4.

**Comment by tmk1991** [comment]
Agreed with @wilk-polarny  - blocking issue

**Current behavior:**
When clicking between inputs on a page, the tab bar will randomly decide to show and hide above the keyboard.

**Expected behavior:**
control the behavior of the tab bar (ideally, don't show it at all).

**Comment by JohnnyWombwell** [comment]
Hi all

Is there a known workaround for this? 

We have tried manually hiding the tab bar on keyboard events but the results are pretty ugly (flickering etc).

Thanks
John

Versions as follows:

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

**Comment by wilk-polarny** [comment]
@liamdebeasi https://www.youtube.com/watch?v=Mi57d50pCUw
:)

**Comment by liamdebeasi** [comment]
@wilk-polarny Ok, that made me laugh 😄 

In terms of a workaround, you will likely want to make sure you move that input back up into the visible area so no scrolling is required. We are actively working on some keyboard fixes that will hopefully address this issue.

I will keep you posted!

**Comment by Spinnenzunge** [comment]
@liamdebeasi Can you also consider adding a class or something to the ion-app component so other components can be styled if keyboard is open (e.g. hide ion-footer)

**Comment by xiexin36** [comment]
Any update about this issue？

**Comment by VIMHaos** [comment]
This issue is still present - v4.6.0 ,(

**Comment by ThomasKi93** [comment]
Issue still present for v4.6.2

**Comment by neelz040** [comment]
Issue still present with v4.7.4

**Comment by wilk-polarny** [comment]
For magical reasons, the issue is gone for me with Ionic v4.9.0 and the latest ionic keyboard plugin.
I don't know what solved this. Upgrading to 4.9.0 with Angular 8, or the keyboard plugin (or both).

Can anyone confirm?

**Comment by VIMHaos** [comment]
@wilk-polarny thanks for information,
Yes it's resolved for us, by ionic@4.8.1 and cordova-plugin-ionic-keyboard@2.2.0
Angular version still is 7.2.15

**Comment by wilk-polarny** [comment]
@liamdebeasi , looks like this has been resolved by cordova-plugin-ionic-keyboard v2.2.0 ?
Closing.

**Comment by rubiktubik** [comment]
Issue not solved for me with cordova-plugin-ionic-keyboard v2.2.0. :-( 
Tab-Bar reappears when i switch from one input to another. 

I'am using angular 7.0.1 and cordova-ios 5.0.1
