### ISSUE TITLE
bug: Buttons no longer align with ion-searchbar

### ISSUE THREAD

**Issue by rossholdway** [ionic-team/ionic#19502]
# Bug Report

**Ionic version:**

[x] **4.10.0**

**Current behavior:**
Add an `ion-buttons` next to an `ion-searchbar` component within a toolbar. On iOS they no longer align in v4.10.0. Unless there is a different way to align buttons next to a ion-searchbar that I am unaware of I believe this is a bug?

**Expected behavior:**
I'd expect buttons within `ion-buttons` to align with the searchbar on iOS.

![Screenshot 2019-09-30 at 17 35 10](https://user-images.githubusercontent.com/2728159/65898508-9d53be00-e3a9-11e9-9ab9-5a89c1c6fb89.png)

**Steps to reproduce:**

**Related code:**
```
<ion-header>
  <ion-toolbar>
    <ion-searchbar></ion-searchbar>
    <ion-buttons slot="end">
      <ion-button (click)="goBack()">
        Cancel
      </ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
```

**Other information:**
I believe this is due to the addition of https://github.com/ionic-team/ionic/commit/e27962dcaf98bfb1f4c026df5a8c525ee3773261#diff-d7830cbb2e9f6ba7efe16e29aaac9c6b specifically the `padding-top: 1px !important;`.

**Comment by brandyscarney** [comment]
Thanks for the issue! Are you using a custom cancel button?

**Comment by rossholdway** [comment]
Hi @brandyscarney

Yes, I am using a custom button because I need it to call a function on tap. I believe the button that’s provided by the ion-searchbar doesn’t allow me to do this.

**Comment by brandyscarney** [comment]
@rossholdway Anything in particular you're trying to do? You should be able to listen to the `ionCancel` event and change the visibility of it that way. Here's a sample Codepen: https://codepen.io/brandyscarney/pen/PoYrJNK?editors=1111

We can fix the alignment of buttons next to the toolbar but they will but up higher by the searchbar since this is updated to match the iOS spec.

**Comment by Anthony2539** [comment]
Hi @brandyscarney,

I have the same issue

![image](https://user-images.githubusercontent.com/5879052/65937557-8d2af580-e420-11e9-84b2-31bb2f11e116.png)
**Related Code:**
`
<ion-header>
    <ion-toolbar>
        <ion-buttons slot="start">
            <ion-back-button text=""></ion-back-button>
          </ion-buttons>
        <ion-searchbar #autofocus debounce="500" color="primary" placeholder="Rechercher un vin" (ionChange)="search($event)"></ion-searchbar>
        <ion-buttons slot="end">
            <ion-button (click)="showFilterChoice()" color="primary" fill="outline">Filtres</ion-button>
          </ion-buttons>
      </ion-toolbar>
  </ion-header>
`

**Comment by mateusduraes** [comment]
Same issue here.

By debugging I realize that the padding-top of ion-searchbar was removed, it is probably related to the issue.

**Comment by rossholdway** [comment]
@brandyscarney Amazing. Thanks for the codepen. Didn't realise there was an `ionCancel` event available for the in built `ion-searchbar` button. Eveything alings for me now, although I guess it might be worth looking into a CSS fix for custom buttons e.g. in Anthony2539's example above he has two buttons to align in the toolbar (back and filters).

**Comment by brandyscarney** [comment]
Thanks for the feedback! So like I said, we can update the buttons so that they are aligned with the searchbar but this will put them closer to the top. This is due to the iOS spec which normally does not include buttons by a searchbar. Here's a picture of the spec to see where the numbers come from:

<img width="600" alt="Screen Shot 2019-10-02 at 10 25 35 AM" src="https://user-images.githubusercontent.com/6577830/66053149-c8502600-e4ff-11e9-81f3-08daea127294.png">

And here are some examples of the searchbar in a toolbar by itself:

![IMG_8140](https://user-images.githubusercontent.com/6577830/66053410-43b1d780-e500-11e9-9ccf-9b19447cfcae.jpg)
![IMG_8141](https://user-images.githubusercontent.com/6577830/66053411-43b1d780-e500-11e9-9058-ada0d5bf9632.jpg)

I'll look into a fix for the buttons. 🙂

**Comment by brandyscarney** [comment]
As a workaround until the fix is in you can target them with this CSS:

```
ion-buttons {
  align-self: start;
}
```

This should mostly center them, still making sure it works properly. 🙂 

https://codepen.io/brandyscarney/pen/WNeVJGw

**Comment by brandyscarney** [comment]
This has been fixed in `master`, we're planning a `4.10.1` release with this in it on Friday. In the meantime, please use this dev build if you need it sooner: `4.11.0-dev.201910021623.cdfd82a`

Thanks everyone!

**Comment by thiennm2905** [comment]
still occur on 4.11.0-dev.201910081329.02c1724
<img width="375" alt="Screen Shot 2019-10-09 at 05 00 54" src="https://user-images.githubusercontent.com/50475853/66436662-e19e2880-ea51-11e9-86b3-843a5e898309.png">

**Comment by brandyscarney** [comment]
Please use the exact dev build I posted, other dev builds weren't made with the same branch.

**Comment by brandyscarney** [comment]
Actually, it was published with `4.10.1`: https://ionicframework.com/docs/release-notes#4.10.1

**Comment by thiennm2905** [comment]
I just use version 4.10.2 before try to use dev version, and I dont know why you fixed height and padding with important :(

**Comment by thiennm2905** [comment]
searchbar align with cancel button, but not with others items inside ion-toolbar

**Comment by thiennm2905** [comment]
a simple code, please check it
`
<ion-header>
  <ion-toolbar>
    <ion-chip [outline]="true" color="app" slot="start" (click)="picker.open()">
      <ion-datetime #picker [(ngModel)]="pickedDate" (ngModelChange)="pickDate()"
                    displayFormat="DD-MM-YYYY" pickerFormat="DD-MM-YYYY"
                    cancelText="thoát" doneText="chọn"
                    style="display: none;"></ion-datetime>
      {{pickedDate | date:'dd/MM/yyyy'}}
    </ion-chip>
    <ion-searchbar placeholder="nhập tên, sđt" [(ngModel)]="keyword" (ngModelChange)="search()"></ion-searchbar>
    <ion-buttons slot="end">
      <ion-button (click)="clearData()" size="small">
        <ion-icon color="danger" slot="icon-only" size="small" name="trash"></ion-icon>
      </ion-button>
      <ion-button (click)="updateData()" size="small">
        <ion-icon slot="icon-only" name="refresh" size="small"></ion-icon>
      </ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
`

**Comment by brandyscarney** [comment]
The searchbar has to have `!important` on it because it's a scoped component, so that's the way to make it override its default styles. This was done to match the `iOS` spec, see my comment here: https://github.com/ionic-team/ionic/issues/19502#issuecomment-537522707

We always align our components to match native. iOS doesn't actually have the concept of chips, but I can add some styles to align it but it will be on the top.

**Comment by thiennm2905** [comment]
I know your mind but I think height and padding-bottom should not have important, it's make me impossible to custom my style ^^!
thanks for your helps

**Comment by brandyscarney** [comment]
Okay I found a way to move the CSS so that `!important` wouldn't be needed and adjusted the styles for chip. I'm working on a dev build, ran into some issues.

**Comment by brandyscarney** [comment]
Can you try this dev build please: `4.11.0-dev.201910082331.57ee7eb`

**Comment by thiennm2905** [comment]
I'm really grateful for your helps ^_^

**Comment by thiennm2905** [comment]
sample code
`<ion-header>
  <ion-toolbar>
    <ion-chip [outline]="true" color="app" slot="start" (click)="picker.open()">
      <ion-datetime #picker [(ngModel)]="pickedDate" (ngModelChange)="pickDate()"
                    displayFormat="DD-MM-YYYY" pickerFormat="DD-MM-YYYY"
                    cancelText="thoát" doneText="chọn"
                    style="display: none;"></ion-datetime>
      {{pickedDate | date:'dd/MM/yyyy'}}
    </ion-chip>
    <ion-searchbar placeholder="nhập tên, sđt" [(ngModel)]="keyword" (ngModelChange)="search()" showCancelButton="always"></ion-searchbar>
    <ion-buttons slot="end">
      <ion-button (click)="clearData()" size="small">
        <ion-icon color="danger" slot="icon-only" size="small" name="trash"></ion-icon>
      </ion-button>
      <ion-button (click)="updateData()" size="small">
        <ion-icon slot="icon-only" name="refresh" size="small"></ion-icon>
      </ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
<ion-toolbar>
  <ion-chip [outline]="true" color="app" slot="start" (click)="picker.open()">
    <ion-datetime #picker [(ngModel)]="pickedDate" (ngModelChange)="pickDate()"
                  displayFormat="DD-MM-YYYY" pickerFormat="DD-MM-YYYY"
                  cancelText="thoát" doneText="chọn"
                  style="display: none;"></ion-datetime>
    {{pickedDate | date:'dd/MM/yyyy'}}
  </ion-chip>
  <ion-searchbar placeholder="nhập tên, sđt" [(ngModel)]="keyword" (ngModelChange)="search()"></ion-searchbar>
  <ion-buttons slot="end">
    <ion-button (click)="clearData()" size="small">
      <ion-icon color="danger" slot="icon-only" size="small" name="trash"></ion-icon>
    </ion-button>
    <ion-button (click)="updateData()" size="small">
      <ion-icon slot="icon-only" name="refresh" size="small"></ion-icon>
    </ion-button>
  </ion-buttons>
</ion-toolbar>`
<img width="374" alt="Screen Shot 2019-10-10 at 11 58 30" src="https://user-images.githubusercontent.com/50475853/66540350-ba308400-eb55-11e9-85c9-87bf2d8fc0cf.png">
<img width="1240" alt="Screen Shot 2019-10-10 at 11 59 46" src="https://user-images.githubusercontent.com/50475853/66540362-c0befb80-eb55-11e9-844c-b0fe8530875e.png">
<img width="251" alt="Screen Shot 2019-10-10 at 12 00 14" src="https://user-images.githubusercontent.com/50475853/66540369-c4eb1900-eb55-11e9-9c24-7387e845bdd7.png">
@brandyscarney

**Comment by robingenz** [comment]
The alignment of the search bar is still not optimal.
![image](https://user-images.githubusercontent.com/13857929/66740463-92059580-ee73-11e9-9bd4-cfed6d83d840.png)

Example: https://codepen.io/robingenz/pen/XWWdrRX

Will this be fixed?

**Comment by brandyscarney** [comment]
Please create a new issue if you are still running into a bug. The original issue has been resolved so I am going to lock this.

As I mentioned [above](https://github.com/ionic-team/ionic/issues/19502#issuecomment-537522707) the padding on the searchbar matches the iOS spec and is correct. It will not be changed. Please use custom padding in your app if you want it to look different.
