### ISSUE TITLE
bug: Ion-slides doesn't initiate itself correctly after second call

### ISSUE THREAD

**Issue by MarcDelrue** [ionic-team/ionic#21163]
# Bug Report

**Ionic version:**

[x] **4.x**

I have a problem on my app using ion-slides. On a page, I wish to click on a router link and it brings me on a new page with a ion-slide and depending on a parameter from the parent page, it set an initialSlide.

**Current behavior:**

The first time the page with the ion-slides is called, everything works fine, the slide is initiated with the index I gave. But if I try to go back (with navController), select a different index of slide to initiate with, when the page with the slide is called again. The ion-slide doesn't take any options. The slides.getActiveIndex (slides being a viewChild on ion-slides) returns undefined. Seems like the ion-slide is not killed correctly when I go back and when I call it again I can't seem to use it with events (slides.slideTo doesn't work).

**Expected behavior:**

Everytime the page with ion-slides is loaded, the ion-slide should initiate itself on the slide I asked

**Steps to reproduce:**

From parent Page -> use router.navitage with in query params the id of the slide
in the page with the ion-slides -> take parameter of query params and set it to initalSlide, everything works correctly
-> go back with navController (to get the animation)
From parent Page -> go again to the page with ion-slide with an other parameter
in the page with the ion-slides -> everything is loaded but the ion-slides is like set to default and I can't interract with it with the events and methods available

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has already been resolved via #20899, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by elvisgraho** [comment]
The issue is still not fixes with Ionic 5.1.1 
The commit says it is "merged", but he bug is still there.
